FROM eclipse-temurin:11-jre
WORKDIR /app
COPY otp-1.5.0-shaded.jar ./otp.jar

ENV ROUTER_ID=default

CMD ["sh", "-c", "java -Xmx4G -jar otp.jar --graphs ./graphs --router $ROUTER_ID --server --port 8080"]
