"""
Django settings for mobilys_BE project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
from datetime import timedelta
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])
DB_TIMING_LOG_ENABLED = env.bool("DB_TIMING_LOG_ENABLED", False)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'gtfs',
    'corsheaders',
    'visualization',
    'simulation',
    'user',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "mobilys_BE.shared.request_logging.RequestIdMiddleware",
    "mobilys_BE.shared.request_logging.DbTimingMiddleware",
    "mobilys_BE.shared.request_logging.StructuredRequestLogMiddleware",
]

if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'mobilys_BE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mobilys_BE.wsgi.application'

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Avoid clashing with domain-specific query params like `?format=xlsx`.
    # DRF's renderer override stays available via `?drf_format=json` if needed.
    'URL_FORMAT_OVERRIDE': 'drf_format',
}

MLIT_API_KEY = env('MLIT_API_KEY', default='C6h1zUCPfgw4QEq~RRTCqrXnKFAFLgye')
MLIT_API_URL = env('MLIT_API_URL', default='https://data-platform.mlit.go.jp/api/v1/')
MLIT_API_TIMEOUT = env('MLIT_API_TIMEOUT', default=10)
ESTAT_API_KEY = env('ESTAT_API_KEY', default='1dbfe83ca140c87b6373a1e8a65b7dcf97fa41be')
ESTAT_API_URL = env('ESTAT_API_URL', default='https://api.e-stat.go.jp/rest/3.0/app/json/getStatsData')

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.office365.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'muhammad.fadlil@tk.pacific.co.jp'      # ganti dengan email kamu
# EMAIL_HOST_PASSWORD = 'password'         # ganti dengan password email kamu (atau app password jika 2FA)
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = 'muhammad.fadlil@tk.pacific.co.jp'


CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

 
#csv file
SIMULATION_IC_TABLE = env("SIMULATION_IC_TABLE", default="ic_boardings")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "json_message": {
            "format": "%(message)s",
        },
        "verbose": {
            "format": "{levelname} {asctime} {name} {module} {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console_json": {
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "json_message",
        },
        "console_verbose": {
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "verbose",
        },
    },

    "root": {
        "handlers": ["console_verbose"],
        "level": "INFO",
    },

    "loggers": {
        "request": {
            "handlers": ["console_json"],
            "level": "INFO",
            "propagate": False,
        },

        "mobilys_BE": {
            "handlers": ["console_json"],
            "level": "DEBUG",
            "propagate": False,
        },

        "django.request": {
            "handlers": ["console_verbose"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

REQUEST_LOG_EXCLUDE_PREFIXES = [
    "/api/visualization/tile-proxy",
    "/api/gtfs/data/notifications",
    "/health",
]

REQUEST_LOG_BODY_ENABLED = env.bool("REQUEST_LOG_BODY_ENABLED", False)
REQUEST_LOG_BODY_MAX_BYTES = env.int("REQUEST_LOG_BODY_MAX_BYTES", 65536)
REQUEST_LOG_BODY_METHODS = ("POST", "PUT", "PATCH")

REQUEST_LOG_BODY_ALLOWLIST = []

REQUEST_LOG_BODY_REDACT_KEYS = ("password", "token", "access", "refresh", "authorization")
