# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-09-18 01:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gtfs', '0025_alter_fareattribute_agency_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='gtfs.scenario')),
            ],
            options={
                'db_table': 'simulation',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OperatingEconomics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(help_text='GTFS routes.route_id', max_length=64)),
                ('route_length_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost_per_vkm_yen', models.DecimalField(decimal_places=2, default=Decimal('520.90'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fare_override_yen', models.PositiveIntegerField(blank=True, null=True)),
                ('delta_vehicle_km_per_day', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('delta_cost_yen_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('delta_revenue_yen_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('net_per_day_yen', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('annual_benefit_k_yen', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_economics', to='simulation.simulation')),
            ],
            options={
                'db_table': 'operating_economics',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['scenario', 'id'], name='sim_scn_id_idx'),
        ),
        migrations.AddIndex(
            model_name='operatingeconomics',
            index=models.Index(fields=['simulation', 'route_id'], name='ops_sim_route_idx'),
        ),
        migrations.AddConstraint(
            model_name='operatingeconomics',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id'), name='uniq_ops_sim_route'),
        ),
    ]
