# Generated by Django 5.2.1 on 2025-09-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingeconomics',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('success', 'success'), ('fail', 'fail')], db_index=True, default='draft', max_length=16),
        ),
    ]
