# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-09-18 07:26

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_operatingeconomics_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrmKasyoDedup',
            fields=[
                ('join_key_csv', models.TextField(primary_key=True, serialize=False)),
                ('matchcode_raw', models.TextField(blank=True, null=True)),
                ('road_name', models.TextField(blank=True, null=True)),
                ('length_km_csv', models.FloatField(blank=True, null=True)),
                ('vol_up_12h', models.IntegerField(blank=True, null=True)),
                ('vol_dn_12h', models.IntegerField(blank=True, null=True)),
                ('vol_up_24h', models.IntegerField(blank=True, null=True)),
                ('vol_dn_24h', models.IntegerField(blank=True, null=True)),
                ('speed_up_kmh', models.FloatField(blank=True, null=True)),
                ('speed_dn_kmh', models.FloatField(blank=True, null=True)),
                ('lanes', models.IntegerField(blank=True, null=True)),
                ('signal_density_per_km', models.FloatField(blank=True, null=True)),
                ('congestion_index', models.FloatField(blank=True, null=True)),
                ('matchcode_digits', models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                'db_table': 'drm_kasyo_dedup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrmKasyoRaw',
            fields=[
                ('join_key_csv', models.TextField(primary_key=True, serialize=False)),
                ('matchcode_raw', models.TextField(blank=True, null=True)),
                ('road_name', models.TextField(blank=True, null=True)),
                ('length_km_csv', models.FloatField(blank=True, null=True)),
                ('vol_up_12h', models.IntegerField(blank=True, null=True)),
                ('vol_dn_12h', models.IntegerField(blank=True, null=True)),
                ('vol_up_24h', models.IntegerField(blank=True, null=True)),
                ('vol_dn_24h', models.IntegerField(blank=True, null=True)),
                ('speed_up_kmh', models.FloatField(blank=True, null=True)),
                ('speed_dn_kmh', models.FloatField(blank=True, null=True)),
                ('lanes', models.IntegerField(blank=True, null=True)),
                ('signal_density_per_km', models.FloatField(blank=True, null=True)),
                ('congestion_index', models.FloatField(blank=True, null=True)),
                ('matchcode_digits', models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                'db_table': 'drm_kasyo_raw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrmLinks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('join_key', models.TextField(blank=True, null=True)),
                ('survey_unit', models.TextField(blank=True, null=True)),
                ('matchcode_shp', models.TextField(blank=True, null=True)),
                ('section_code_csv', models.TextField(blank=True, null=True)),
                ('road_name', models.TextField(blank=True, null=True)),
                ('length_m', models.IntegerField(blank=True, null=True)),
                ('lanes', models.IntegerField(blank=True, null=True)),
                ('updown_cd', models.IntegerField(blank=True, null=True)),
                ('speed_code', models.IntegerField(blank=True, null=True)),
                ('toll_cd', models.IntegerField(blank=True, null=True)),
                ('access_cd', models.IntegerField(blank=True, null=True)),
                ('motor_only_cd', models.IntegerField(blank=True, null=True)),
                ('travel_speed_model_kmh', models.FloatField(blank=True, null=True)),
                ('speed_up_kmh', models.FloatField(blank=True, null=True)),
                ('speed_dn_kmh', models.FloatField(blank=True, null=True)),
                ('vol_up_24h', models.IntegerField(blank=True, null=True)),
                ('vol_dn_24h', models.IntegerField(blank=True, null=True)),
                ('traffic24_total', models.IntegerField(blank=True, null=True)),
                ('vol_up_12h', models.IntegerField(blank=True, null=True)),
                ('vol_dn_12h', models.IntegerField(blank=True, null=True)),
                ('traffic12_total', models.IntegerField(blank=True, null=True)),
                ('signal_density_per_km', models.FloatField(blank=True, null=True)),
                ('congestion_index', models.FloatField(blank=True, null=True)),
                ('source', models.BigIntegerField(blank=True, null=True)),
                ('target', models.BigIntegerField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('reverse_cost', models.FloatField(blank=True, null=True)),
                ('imputed_from_join_key', models.TextField(blank=True, null=True)),
                ('imputation_method', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drm_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrmLinksRaw',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('survey_unit', models.TextField(blank=True, null=True)),
                ('matchcode', models.TextField(blank=True, null=True)),
                ('link_cd', models.BigIntegerField(blank=True, null=True)),
                ('link_len', models.IntegerField(blank=True, null=True)),
                ('lanes_cd', models.IntegerField(blank=True, null=True)),
                ('speed_code', models.IntegerField(blank=True, null=True)),
                ('access_cd', models.IntegerField(blank=True, null=True)),
                ('toll_cd', models.IntegerField(blank=True, null=True)),
                ('motor_only_cd', models.IntegerField(blank=True, null=True)),
                ('updown_cd', models.IntegerField(blank=True, null=True)),
                ('traffic12', models.IntegerField(blank=True, null=True)),
                ('travel_speed_dkmh', models.IntegerField(blank=True, null=True)),
                ('w12h', models.IntegerField(blank=True, null=True)),
                ('w24h', models.IntegerField(blank=True, null=True)),
                ('h12h', models.IntegerField(blank=True, null=True)),
                ('h24h', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('norm_survey', models.TextField(blank=True, null=True)),
                ('norm_matchcode', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drm_links_raw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrmLinksVerticesPgr',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('the_geom', django.contrib.gis.db.models.fields.PointField(db_column='the_geom', srid=4326)),
            ],
            options={
                'db_table': 'drm_links_vertices_pgr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(help_text='GTFS routes.route_id', max_length=64)),
                ('shape_id', models.CharField(blank=True, max_length=128)),
                ('delta_demand_persons_day', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('car_share', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('start_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('start_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('end_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('end_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('success', 'success'), ('fail', 'fail')], db_index=True, default='draft', max_length=16)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_routings', to='simulation.simulation')),
            ],
            options={
                'db_table': 'car_routing',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CarRoutingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('link_id', models.BigIntegerField()),
                ('section_id', models.CharField(blank=True, max_length=64, null=True)),
                ('road_name', models.TextField(blank=True, null=True)),
                ('length_m', models.IntegerField(blank=True, null=True)),
                ('lanes', models.IntegerField(blank=True, null=True)),
                ('speed_up_kmh', models.FloatField(blank=True, null=True)),
                ('speed_dn_kmh', models.FloatField(blank=True, null=True)),
                ('baseline_cars_per_day', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('delta_cars_per_day', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('after_cars_per_day', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('cost_min', models.FloatField(blank=True, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('car_routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='simulation.carrouting')),
            ],
            options={
                'db_table': 'car_routing_segment',
                'ordering': ['car_routing', 'seq'],
            },
        ),
        migrations.AddIndex(
            model_name='carrouting',
            index=models.Index(fields=['simulation', 'route_id'], name='car_routing_sim_route_idx'),
        ),
        migrations.AddConstraint(
            model_name='carrouting',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id'), name='uniq_car_routing_sim_route'),
        ),
        migrations.AddIndex(
            model_name='carroutingsegment',
            index=models.Index(fields=['car_routing', 'seq'], name='car_routing_seg_idx'),
        ),
        migrations.AddIndex(
            model_name='carroutingsegment',
            index=models.Index(fields=['link_id'], name='car_routing_seg_link_idx'),
        ),
        migrations.AddConstraint(
            model_name='carroutingsegment',
            constraint=models.UniqueConstraint(fields=('car_routing', 'seq'), name='uniq_car_routing_seg_seq'),
        ),
    ]
