# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-09-25 07:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0025_alter_fareattribute_agency_id'),
        ('simulation', '0003_drmkasyodedup_drmkasyoraw_drmlinks_drmlinksraw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitCalculations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(db_index=True, max_length=128)),
                ('shape_id', models.CharField(db_index=True, max_length=128)),
                ('matchcode_shp', models.TextField(db_index=True)),
                ('section_code_csv', models.CharField(blank=True, max_length=64, null=True)),
                ('road_name', models.TextField(blank=True, null=True)),
                ('AJ', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('AL', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('AP', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('AR', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('AU', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('AW', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'benefit_calculations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RidershipChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(help_text='GTFS routes.route_id', max_length=64)),
                ('day_type', models.CharField(choices=[('weekday', 'weekday'), ('saturday', 'saturday'), ('sunday', 'sunday'), ('holiday', 'holiday')], db_index=True, default='weekday', max_length=16)),
                ('baseline_riders_per_day', models.DecimalField(decimal_places=2, help_text='D0 (IC riders/day)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('baseline_trips_per_day', models.DecimalField(decimal_places=2, help_text='B0 (trips/day)', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('delta_trips_per_day', models.DecimalField(decimal_places=2, help_text='ΔB (change in trips/day)', max_digits=9)),
                ('sensitivity_epsilon', models.DecimalField(decimal_places=3, help_text='ε (sensitivity factor)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('delta_riders_per_day', models.IntegerField(blank=True, help_text='ΔD (change in riders/day, computed)', null=True)),
                ('gtfs_service_id', models.CharField(blank=True, max_length=64, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('calc_meta', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('success', 'success'), ('fail', 'fail')], db_index=True, default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ridership_change',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SegmentSpeedMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(db_index=True, max_length=128)),
                ('shape_id', models.CharField(db_index=True, max_length=128)),
                ('matchcode_shp', models.TextField(db_index=True)),
                ('section_code_csv', models.CharField(blank=True, max_length=64, null=True)),
                ('road_name', models.TextField(blank=True, null=True)),
                ('speed_before_kmh', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('speed_after_kmh', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('time_per_vehicle_before_h', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('time_per_vehicle_after_h', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_time_before_vehicle_h', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_time_after_vehicle_h', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'segment_speed_metrics',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='simulation',
            name='duplicated_scenario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='duplicated_simulations', to='gtfs.scenario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='original_scenario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='original_simulations', to='gtfs.scenario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='gtfs.scenario'),
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['original_scenario', 'id'], name='sim_orig_scn_id_idx'),
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['duplicated_scenario', 'id'], name='sim_dupl_scn_id_idx'),
        ),
        migrations.AddField(
            model_name='benefitcalculations',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_calculations', to='simulation.simulation'),
        ),
        migrations.AddField(
            model_name='ridershipchange',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ridership_changes', to='simulation.simulation'),
        ),
        migrations.AddField(
            model_name='segmentspeedmetrics',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_speed_metrics', to='simulation.simulation'),
        ),
        migrations.AddIndex(
            model_name='benefitcalculations',
            index=models.Index(fields=['simulation', 'route_id', 'shape_id'], name='benefit_sim_route_shape_idx'),
        ),
        migrations.AddIndex(
            model_name='benefitcalculations',
            index=models.Index(fields=['matchcode_shp'], name='benefit_matchcode_idx'),
        ),
        migrations.AddConstraint(
            model_name='benefitcalculations',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id', 'shape_id', 'matchcode_shp'), name='uniq_benefit_sim_route_shape_match'),
        ),
        migrations.AddIndex(
            model_name='ridershipchange',
            index=models.Index(fields=['simulation', 'route_id', 'day_type'], name='ridership_sim_route_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='ridershipchange',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id', 'day_type'), name='uniq_rc_sim_route_day'),
        ),
        migrations.AddIndex(
            model_name='segmentspeedmetrics',
            index=models.Index(fields=['simulation', 'route_id', 'shape_id'], name='segm_sim_route_shape_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentspeedmetrics',
            index=models.Index(fields=['matchcode_shp'], name='segm_matchcode_idx'),
        ),
        migrations.AddConstraint(
            model_name='segmentspeedmetrics',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id', 'shape_id', 'matchcode_shp'), name='uniq_segm_metrics_sim_route_shape_match'),
        ),
    ]
