# Generated by Django 5.2.1 on 2025-09-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0004_benefitcalculations_ridershipchange_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefitcalculations',
            old_name='AJ',
            new_name='operating_cost_reduction_after',
        ),
        migrations.RenameField(
            model_name='benefitcalculations',
            old_name='AL',
            new_name='operating_cost_reduction_before',
        ),
        migrations.RenameField(
            model_name='benefitcalculations',
            old_name='AP',
            new_name='traffic_accident_reduction_after',
        ),
        migrations.RenameField(
            model_name='benefitcalculations',
            old_name='AR',
            new_name='traffic_accident_reduction_before',
        ),
        migrations.RenameField(
            model_name='benefitcalculations',
            old_name='AU',
            new_name='travel_time_savings_after',
        ),
        migrations.RenameField(
            model_name='benefitcalculations',
            old_name='AW',
            new_name='travel_time_savings_before',
        ),
    ]
