# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-09-25 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0005_rename_aj_benefitcalculations_operating_cost_reduction_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('success', 'success'), ('fail', 'fail')], default='draft', max_length=16),
        ),
        migrations.CreateModel(
            name='SimulationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_id', models.CharField(max_length=128)),
                ('sensitivity_up', models.FloatField()),
                ('sensitivity_down', models.FloatField()),
                ('trip_cost', models.FloatField()),
                ('car_share', models.FloatField()),
                ('time_value_yen_per_min_per_vehicle', models.FloatField()),
                ('source_file_name', models.CharField(blank=True, max_length=255)),
                ('source_file_size', models.BigIntegerField(default=0)),
                ('source_file_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('success', 'success'), ('fail', 'fail')], default='success', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='input', to='simulation.simulation')),
            ],
        ),
    ]
