# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-09-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0006_simulation_status_simulationinput'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='carrouting',
            name='uniq_car_routing_sim_route',
        ),
        migrations.RemoveIndex(
            model_name='carrouting',
            name='car_routing_sim_route_idx',
        ),
        migrations.AddIndex(
            model_name='carrouting',
            index=models.Index(fields=['simulation', 'route_id', 'shape_id'], name='car_routing_sim_rsshape_idx'),
        ),
        migrations.AddConstraint(
            model_name='carrouting',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id', 'shape_id'), name='uniq_car_routing_sim_route'),
        ),
    ]
