# Generated by Django 5.2.1 on 2025-09-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0007_remove_carrouting_uniq_car_routing_sim_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrouting',
            name='direction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
