# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-09-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0008_carrouting_direction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitcalculations',
            name='direction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benefitcalculations',
            name='service_id',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segmentspeedmetrics',
            name='direction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentspeedmetrics',
            name='service_id',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
