# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-09-29 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0009_benefitcalculations_direction_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulationinput',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='benefitcalculations',
            name='uniq_benefit_sim_route_shape_match',
        ),
        migrations.RemoveConstraint(
            model_name='carrouting',
            name='uniq_car_routing_sim_route',
        ),
        migrations.RemoveConstraint(
            model_name='operatingeconomics',
            name='uniq_ops_sim_route',
        ),
        migrations.RemoveConstraint(
            model_name='ridershipchange',
            name='uniq_rc_sim_route_day',
        ),
        migrations.RemoveConstraint(
            model_name='segmentspeedmetrics',
            name='uniq_segm_metrics_sim_route_shape_match',
        ),
        migrations.RenameIndex(
            model_name='carrouting',
            new_name='car_routing_sim_r_shp_ip_idx',
            old_name='car_routing_sim_rsshape_idx',
        ),
        migrations.RenameIndex(
            model_name='operatingeconomics',
            new_name='ops_sim_route_input_idx',
            old_name='ops_sim_route_idx',
        ),
        migrations.AddField(
            model_name='benefitcalculations',
            name='simulation_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefit_calculations_by_input', to='simulation.simulationinput'),
        ),
        migrations.AddField(
            model_name='carrouting',
            name='simulation_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_routings_by_input', to='simulation.simulationinput'),
        ),
        migrations.AddField(
            model_name='operatingeconomics',
            name='simulation_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_economics_by_input', to='simulation.simulationinput'),
        ),
        migrations.AddField(
            model_name='ridershipchange',
            name='simulation_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ridership_changes_by_input', to='simulation.simulationinput'),
        ),
        migrations.AddField(
            model_name='segmentspeedmetrics',
            name='simulation_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segment_speed_metrics_by_input', to='simulation.simulationinput'),
        ),
        migrations.AlterField(
            model_name='simulationinput',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='simulation.simulation'),
        ),
        migrations.AddIndex(
            model_name='benefitcalculations',
            index=models.Index(fields=['simulation_input'], name='benefit_siminput_idx'),
        ),
        migrations.AddIndex(
            model_name='carrouting',
            index=models.Index(fields=['simulation_input'], name='car_routing_siminput_idx'),
        ),
        migrations.AddIndex(
            model_name='operatingeconomics',
            index=models.Index(fields=['simulation_input'], name='ops_siminput_idx'),
        ),
        migrations.AddIndex(
            model_name='ridershipchange',
            index=models.Index(fields=['simulation_input'], name='ridership_siminput_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentspeedmetrics',
            index=models.Index(fields=['simulation_input'], name='segm_siminput_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationinput',
            index=models.Index(fields=['simulation'], name='sim_input_sim_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationinput',
            index=models.Index(fields=['service_date', 'simulation'], name='sim_input_date_sim_idx'),
        ),
        migrations.AddConstraint(
            model_name='benefitcalculations',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id', 'shape_id', 'matchcode_shp', 'simulation_input'), name='uniq_benefit_sim_input_route_shape_match'),
        ),
        migrations.AddConstraint(
            model_name='carrouting',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id', 'shape_id', 'simulation_input'), name='uniq_car_routing_sim_input_route'),
        ),
        migrations.AddConstraint(
            model_name='operatingeconomics',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id', 'simulation_input'), name='uniq_ops_sim_input_route'),
        ),
        migrations.AddConstraint(
            model_name='ridershipchange',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id', 'day_type', 'simulation_input'), name='uniq_rc_sim_input_route_day'),
        ),
        migrations.AddConstraint(
            model_name='segmentspeedmetrics',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id', 'shape_id', 'matchcode_shp', 'simulation_input'), name='uniq_segm_metrics_sim_input_route_shape_match'),
        ),
        migrations.AlterModelTable(
            name='simulationinput',
            table='simulation_input',
        ),
    ]
