# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-09-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0010_alter_simulationinput_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationinput',
            name='ic_agg',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
