# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-10-01 06:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0011_simulationinput_ic_agg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentspeedmetrics',
            name='time_per_vehicle_after_h',
            field=models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='segmentspeedmetrics',
            name='time_per_vehicle_before_h',
            field=models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
