# Generated by Django 5.2.1 on 2025-10-01 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0011_simulationinput_ic_agg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO2Reduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vkt_before_km_day', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('vkt_after_km_day', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('delta_vkt_km_day', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('ef_car_g_per_vkm', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('co2_tons_per_year', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('success', 'success'), ('fail', 'fail')], db_index=True, default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co2_reductions', to='simulation.simulation')),
                ('simulation_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co2_reductions_by_input', to='simulation.simulationinput')),
            ],
            options={
                'db_table': 'co2_reduction',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['simulation'], name='co2_sim_idx'), models.Index(fields=['simulation_input'], name='co2_siminput_idx')],
                'constraints': [models.UniqueConstraint(fields=('simulation', 'simulation_input'), name='uniq_co2_sim_siminput')],
            },
        ),
    ]
