# Generated by Django 5.2.1 on 2025-10-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0012_alter_segmentspeedmetrics_time_per_vehicle_after_h_and_more'),
        ('simulation', '0012_co2reduction'),
    ]

    operations = [
    ]
