# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-10-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0012_co2reduction'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='co2reduction',
            name='uniq_co2_sim_siminput',
        ),
        migrations.RemoveIndex(
            model_name='co2reduction',
            name='co2_sim_idx',
        ),
        migrations.AddField(
            model_name='co2reduction',
            name='route_id',
            field=models.CharField(db_index=True, default='__PLACEHOLDER', help_text='GTFS routes.route_id', max_length=64),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='co2reduction',
            index=models.Index(fields=['simulation', 'route_id'], name='co2_sim_route_idx'),
        ),
        migrations.AddConstraint(
            model_name='co2reduction',
            constraint=models.UniqueConstraint(fields=('simulation', 'simulation_input', 'route_id'), name='uniq_co2_sim_input_route'),
        ),
    ]
