# Generated by Django 5.2.1 on 2025-10-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0013_merge_20251001_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
