# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-10-02 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0013_remove_co2reduction_uniq_co2_sim_siminput_and_more'),
        ('simulation', '0014_alter_simulation_name'),
    ]

    operations = [
    ]
