# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-10-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0015_merge_20251002_0141'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='benefitcalculations',
            name='uniq_benefit_sim_input_route_shape_match',
        ),
        migrations.RemoveConstraint(
            model_name='carrouting',
            name='uniq_car_routing_sim_input_route',
        ),
        migrations.RemoveConstraint(
            model_name='co2reduction',
            name='uniq_co2_sim_input_route',
        ),
        migrations.RemoveConstraint(
            model_name='operatingeconomics',
            name='uniq_ops_sim_input_route',
        ),
        migrations.RemoveConstraint(
            model_name='ridershipchange',
            name='uniq_rc_sim_input_route_day',
        ),
        migrations.RemoveConstraint(
            model_name='segmentspeedmetrics',
            name='uniq_segm_metrics_sim_input_route_shape_match',
        ),
        migrations.AddField(
            model_name='carrouting',
            name='service_id',
            field=models.CharField(default='平日', max_length=128),
        ),
        migrations.AddField(
            model_name='co2reduction',
            name='service_id',
            field=models.CharField(default='平日', max_length=128),
        ),
        migrations.AddField(
            model_name='operatingeconomics',
            name='service_id',
            field=models.CharField(default='平日', max_length=128),
        ),
        migrations.AlterField(
            model_name='benefitcalculations',
            name='service_id',
            field=models.CharField(default='平日', max_length=128),
        ),
        migrations.AlterField(
            model_name='segmentspeedmetrics',
            name='service_id',
            field=models.CharField(default='平日', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='benefitcalculations',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id', 'shape_id', 'matchcode_shp', 'simulation_input', 'service_id'), name='uniq_benefit_sim_input_route_shape_match'),
        ),
        migrations.AddConstraint(
            model_name='carrouting',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id', 'shape_id', 'simulation_input', 'service_id'), name='uniq_car_routing_sim_input_route'),
        ),
        migrations.AddConstraint(
            model_name='co2reduction',
            constraint=models.UniqueConstraint(fields=('simulation', 'simulation_input', 'route_id', 'service_id'), name='uniq_co2_sim_input_route'),
        ),
        migrations.AddConstraint(
            model_name='operatingeconomics',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id', 'simulation_input', 'service_id'), name='uniq_ops_sim_input_route'),
        ),
        migrations.AddConstraint(
            model_name='ridershipchange',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id', 'day_type', 'simulation_input', 'gtfs_service_id'), name='uniq_rc_sim_input_route_day'),
        ),
        migrations.AddConstraint(
            model_name='segmentspeedmetrics',
            constraint=models.UniqueConstraint(fields=('simulation', 'route_id', 'shape_id', 'matchcode_shp', 'simulation_input', 'service_id'), name='uniq_segm_metrics_sim_input_route_shape_match'),
        ),
    ]
