# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-11-05 03:04

import django.db.models.deletion
import simulation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0016_remove_benefitcalculations_uniq_benefit_sim_input_route_shape_match_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=simulation.models.validation_upload_to)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('service_date', models.CharField(blank=True, default='', max_length=10)),
                ('service_id', models.CharField(blank=True, default='', max_length=128)),
                ('service_ids', models.JSONField(default=list)),
                ('result_json', models.JSONField(default=dict)),
                ('summary_counts', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], db_index=True, default='ok', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_latest', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='simulation.simulation')),
                ('simulation_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_results', to='simulation.simulationinput')),
            ],
            options={
                'db_table': 'simulation_validation_result',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['simulation', 'is_latest'], name='validation_sim_latest_idx'), models.Index(fields=['simulation_input'], name='validation_siminput_idx')],
                'constraints': [models.UniqueConstraint(fields=('simulation', 'version'), name='uniq_validation_sim_version')],
            },
        ),
    ]
