# Generated by Django 5.2.1 on 2025-11-25 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_simulation_user(apps, schema_editor):
    Simulation = apps.get_model("simulation", "Simulation")
    Scenario = apps.get_model("gtfs", "Scenario")

    qs = Simulation.objects.select_related("scenario", "original_scenario")

    for sim in qs.iterator():
        # Priority logic:
        user = None

        if sim.scenario_id and sim.scenario_id is not None:
            user = sim.scenario.user
        elif sim.original_scenario_id and sim.original_scenario_id is not None:
            user = sim.original_scenario.user

        if not user:
            continue

        sim.user_id = user.id
        sim.save(update_fields=["user"])

def reverse_backfill_simulation_user(apps, schema_editor):
    Simulation = apps.get_model("simulation", "Simulation")
    Simulation.objects.update(user=None)

class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0017_simulationvalidationresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.RunPython(backfill_simulation_user, reverse_backfill_simulation_user),
    ]
