# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-12-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0019_alter_simulation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationinput',
            name='default_fare',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
