services:
    mobilys_be:
        build: .
        container_name: mobilys_be
        env_file: [.env]
        ports: ["8000:8000"]
        networks: [app_net]
        entrypoint: ["sh", "/app/entrypoint.sh"]
        volumes: []
        logging:
            driver: awslogs
            options:
                awslogs-region: ap-northeast-1
                awslogs-group: /mobilys/stg/be
                awslogs-create-group: "true"
                awslogs-stream: mobilys_be

    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        container_name: mobilys_db
        ports: ["5432:5432"]
        environment:
            POSTGRES_DB: mobilys
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
        command:
            - "postgres"
            - "-c"
            - "shared_preload_libraries=pg_stat_statements,pg_cron"
            - "-c"
            - "pg_stat_statements.track=all"
            - "-c"
            - "log_min_duration_statement=1000"
            - "-c"
            - "pg_stat_statements.max=5000"
            - "-c"
            - "cron.database_name=mobilys"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks: [app_net]

volumes:
    postgres_data:

networks:
    app_net:
        external: true
