# Generated by Django 5.2.1 on 2025-06-04 01:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(error_messages={'unique': 'このシナリオ名は既に存在します。他の名前を選択してください。'}, max_length=200, unique=True)),
                ('gtfs_filename', models.CharField(max_length=200, null=True)),
                ('source_type', models.IntegerField(choices=[(0, 'API'), (1, 'Local File')])),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('stops_grouping_method', models.CharField(blank=True, choices=[('stop_name', 'stop_name'), ('stop_id', 'stop_id')], default='stop_name', help_text="Method to group stops. Default is 'stop_name'.", max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=200)),
                ('agency_id', models.CharField(max_length=200)),
                ('route_short_name', models.CharField(blank=True, max_length=200)),
                ('route_long_name', models.CharField(blank=True, max_length=200)),
                ('route_desc', models.TextField(blank=True)),
                ('route_type', models.IntegerField(choices=[(0, 'Tram, Streetcar, Light rail'), (1, 'Subway, Metro'), (2, 'Rail (e.g., commuter rail)'), (3, 'Bus'), (4, 'Ferry'), (5, 'Cable car'), (6, 'Gondola, Suspended cable car'), (7, 'Funicular')], default=3)),
                ('route_url', models.URLField(blank=True)),
                ('route_color', models.CharField(blank=True, max_length=6)),
                ('route_text_color', models.CharField(blank=True, max_length=6)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='CalendarDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('exception_type', models.IntegerField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'calendar_dates',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=200)),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
                ('saturday', models.IntegerField()),
                ('sunday', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'calendar',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(max_length=200)),
                ('shape_pt_lat', models.FloatField()),
                ('shape_pt_lon', models.FloatField()),
                ('shape_pt_sequence', models.IntegerField()),
                ('shape_dist_traveled', models.FloatField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'shapes',
            },
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=200)),
                ('stop_code', models.CharField(blank=True, max_length=200)),
                ('stop_name', models.CharField(max_length=200)),
                ('stop_desc', models.TextField(blank=True)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('zone_id', models.CharField(blank=True, max_length=200)),
                ('stop_url', models.URLField(blank=True)),
                ('location_type', models.IntegerField(null=True)),
                ('parent_station', models.CharField(blank=True, max_length=200)),
                ('wheelchair_boarding', models.IntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'stops',
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=200)),
                ('route_id', models.CharField(max_length=200)),
                ('service_id', models.CharField(max_length=200)),
                ('trip_headsign', models.CharField(blank=True, max_length=200)),
                ('trip_short_name', models.CharField(blank=True, max_length=200)),
                ('direction_id', models.IntegerField(null=True)),
                ('block_id', models.CharField(blank=True, max_length=200)),
                ('shape_id', models.CharField(blank=True, max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'trips',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(max_length=200)),
                ('agency_name', models.CharField(max_length=200)),
                ('agency_url', models.URLField(blank=True)),
                ('agency_timezone', models.CharField(blank=True, max_length=50)),
                ('agency_lang', models.CharField(blank=True, max_length=10)),
                ('agency_phone', models.CharField(blank=True, max_length=20)),
                ('agency_fare_url', models.URLField(blank=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'agency',
                'constraints': [models.UniqueConstraint(fields=('agency_id', 'scenario'), name='unique_field_agency_id_scenario')],
            },
        ),
        migrations.CreateModel(
            name='StopIdKeyword',
            fields=[
                ('stop_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('stop_id_keyword', models.CharField(error_messages={'unique': 'このキーワードは既に存在します。他のキーワードを選択してください。'}, max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'stop_id_keyword',
                'unique_together': {('stop_id_keyword', 'scenario')},
            },
        ),
        migrations.CreateModel(
            name='StopIdKeywordMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=200)),
                ('stop_id_group_id', models.IntegerField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'stop_id_keyword_map',
                'unique_together': {('stop_id_group_id', 'stop_id', 'scenario')},
            },
        ),
        migrations.CreateModel(
            name='StopTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=200)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_id', models.CharField(max_length=200)),
                ('stop_sequence', models.IntegerField()),
                ('stop_headsign', models.CharField(blank=True, max_length=200)),
                ('pickup_type', models.IntegerField(null=True)),
                ('drop_off_type', models.IntegerField(null=True)),
                ('shape_dist_traveled', models.FloatField(null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'stop_times',
                'indexes': [models.Index(fields=['trip_id', 'stop_sequence'], name='stop_times_trip_id_fe5890_idx')],
            },
        ),
    ]
