# Generated by Django 5.2.1 on 2025-06-04 03:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteKeywords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'route_keywords',
            },
        ),
        migrations.CreateModel(
            name='RouteKeywordMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=200)),
                ('is_manually_update', models.BooleanField(default=False)),
                ('scenario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.routekeywords')),
            ],
            options={
                'db_table': 'route_keyword_map',
            },
        ),
    ]