# Generated by Django 5.2.1 on 2025-06-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0003_rename_scenario_id_routekeywords_scenario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routekeywordmap',
            old_name='scenario_id',
            new_name='scenario',
        ),
    ]
