# Generated by Django 5.2.1 on 2025-06-05 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0004_rename_scenario_id_routekeywordmap_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopNameKeywordMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=200)),
                ('stop_name_group_id', models.CharField(max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'stop_name_keyword_map',
                'unique_together': {('stop_id', 'stop_name_group_id', 'scenario')},
            },
        ),
        migrations.CreateModel(
            name='StopNameKeywords',
            fields=[
                ('stop_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('stop_name_keyword', models.CharField(error_messages={'unique': 'このキーワードは既に存在します。他のキーワードを選択してください。'}, max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'stop_name_keywords',
                'unique_together': {('stop_name_keyword', 'scenario')},
            },
        ),
    ]
