# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-06-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0005_stopnamekeywordmap_stopnamekeywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='routekeywords',
            name='keyword_color',
            field=models.CharField(default='000000', help_text='Hex color code for the keyword, default is black (000000)', max_length=6),
        ),
    ]
