# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-06-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0006_routekeywords_keyword_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopidkeyword',
            name='stop_id_lat',
            field=models.FloatField(default=0.0, help_text='Latitude for the stop ID'),
        ),
        migrations.AddField(
            model_name='stopidkeyword',
            name='stop_id_long',
            field=models.FloatField(default=0.0, help_text='Longitude for the stop ID'),
        ),
        migrations.AddField(
            model_name='stopidkeywordmap',
            name='is_manually_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stopnamekeywordmap',
            name='is_manually_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stopnamekeywords',
            name='stop_names_lat',
            field=models.FloatField(default=0.0, help_text='Latitude for the stop names'),
        ),
        migrations.AddField(
            model_name='stopnamekeywords',
            name='stop_names_long',
            field=models.FloatField(default=0.0, help_text='Longitude for the stop names'),
        ),
    ]
