# Generated by Django 5.2.1 on 2025-06-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0007_stopidkeyword_stop_id_lat_stopidkeyword_stop_id_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routekeywordmap',
            name='is_manually_update',
        ),
        migrations.RemoveField(
            model_name='stopidkeywordmap',
            name='is_manually_update',
        ),
        migrations.RemoveField(
            model_name='stopnamekeywordmap',
            name='is_manually_update',
        ),
        migrations.AddField(
            model_name='routekeywordmap',
            name='can_automatically_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stopidkeywordmap',
            name='can_automatically_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stopnamekeywordmap',
            name='can_automatically_update',
            field=models.BooleanField(default=True),
        ),
    ]
