# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-06-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0008_remove_routekeywordmap_is_manually_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='end_date',
            field=models.DateField(help_text='The end date for the scenario.', null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='start_date',
            field=models.DateField(help_text='The start date for the scenario.', null=True),
        ),
    ]
