# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-06-11 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0009_scenario_end_date_scenario_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='source_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_scenarios', to='gtfs.scenario'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='source_type',
            field=models.IntegerField(choices=[(0, 'API'), (1, 'Local File'), (2, 'Cloned File')]),
        ),
    ]
