# Generated by Django 5.2.1 on 2025-06-20 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_default_maps_and_profiles(apps, schema_editor):
    Map = apps.get_model('gtfs', 'Map')
    Profile = apps.get_model('gtfs', 'Profile')
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])

    default_maps = [
        {
            "id": "pale",
            "name": "Pale Map（淡色地図）",
            "url": "https://cyberjapandata.gsi.go.jp/xyz/pale/{z}/{x}/{y}.png",
        },
        {
            "id": "std",
            "name": "Standard Map（標準地図）",
            "url": "https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png",
        },
        {
            "id": "photo",
            "name": "Photo Map（シームレス写真）",
            "url": "https://cyberjapandata.gsi.go.jp/xyz/seamlessphoto/{z}/{x}/{y}.jpg",
        },
    ]

    map_objs = {}
    for d in default_maps:
        obj, created = Map.objects.get_or_create(name=d['name'], url=d['url'])
        map_objs[d['id']] = obj

    std_map = map_objs['pale']  # Assigning the 'pale' map as default for all users
    for user in User.objects.all():
        profile, created = Profile.objects.get_or_create(user=user)
        profile.map = std_map
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0011_feedinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'map',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtfs.map')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(add_default_maps_and_profiles),
    ]
