# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-06-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0012_map_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='is_direction_id_generated',
            field=models.BooleanField(default=False, help_text='Indicates if the direction_id was generated automatically.'),
        ),
    ]
