# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-06-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0013_trips_is_direction_id_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='direction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
