# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-07-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0014_alter_trips_direction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='graph_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('built', 'Built'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
