# Generated by Django 5.2.1 on 2025-07-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0015_scenario_graph_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='graph_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('built', 'Built'), ('failed', 'Failed'), ('rebuilding', 'Rebuilding'), ('rebuilt', 'Rebuilt'), ('rebuild_failed', 'Rebuild Failed')], default='pending', max_length=20),
        ),
    ]
