# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-07-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0016_alter_scenario_graph_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='deletion_state',
            field=models.CharField(choices=[('active', 'active'), ('deletion_pending', 'deletion_pending'), ('failed', 'failed')], default='active', max_length=100),
        ),
    ]
