# Generated by Django 5.2.1 on 2025-07-31 01:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0017_scenario_deletion_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('notification_path', models.CharField(help_text='Path to the notification resource', max_length=255)),
                ('scenario_id', models.UUIDField(blank=True, help_text='Scenario ID related to the notification', null=True)),
                ('screen_menu', models.CharField(help_text='Screen menu where the notification will be displayed', max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Optional description for the notification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
