# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-08-04 08:07

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0018_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("table_name", models.CharField(max_length=200)),
                ("field_name", models.CharField(max_length=200)),
                ("field_value", models.TextField(blank=True, default="")),
                ("language", models.CharField(max_length=100)),
                ("translation", models.TextField()),
                ("route_id", models.CharField(blank=True, max_length=200)),
                ("trip_id", models.CharField(blank=True, max_length=200)),
                ("service_id", models.CharField(blank=True, max_length=200)),
                ("stop_id", models.CharField(blank=True, max_length=200)),
                ("shape_id", models.CharField(blank=True, max_length=200)),
                ("feed_info_id", models.CharField(blank=True, max_length=200)),
                ("scenario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="gtfs.scenario")),
            ],
            options={
                "db_table": "translations",
                "indexes": [
                    models.Index(
                        fields=["scenario", "table_name", "field_name", "language"],
                        name="translation_scenari_ced3fa_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                fields=[
                    "scenario",
                    "table_name",
                    "field_name",
                    "language",
                    "route_id",
                    "trip_id",
                    "service_id",
                    "stop_id",
                    "shape_id",
                    "feed_info_id",
                ],
                name="uniq_translation_per_entity_and_lang",
            ),
        ),
    ]
