# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-08-27 00:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='edit_state',
            field=models.CharField(choices=[('original', 'original'), ('edited', 'edited')], default='original', max_length=100),
        ),
        migrations.AddField(
            model_name='scenario',
            name='edited_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, help_text='Path to the edited GTFS data file.', size=None),
        ),
    ]
    