# Generated by Django 5.2.1 on 2025-08-05 07:56

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0019_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(max_length=200)),
                ('fare_id', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_type', models.CharField(max_length=10)),
                ('payment_method', models.IntegerField(blank=True, help_text='0 = paid on board, 1 = paid before boarding, or your own codes', null=True)),
                ('transfers', models.IntegerField(blank=True, help_text='Number of permitted transfers, if any', null=True)),
                ('transfer_duration', models.IntegerField(blank=True, help_text='Seconds allowed for transfer window', null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'fare_attributes',
                'unique_together': {('scenario', 'fare_id')},
            },
        ),
    ]
