# Generated by Django 5.2.1 on 2025-08-05 08:10

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0020_fareattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(blank=True, max_length=200)),
                ('origin_id', models.CharField(blank=True, max_length=200)),
                ('destination_id', models.CharField(blank=True, max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('fare_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='gtfs.fareattribute')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'fare_rules',
                'unique_together': {('scenario', 'fare_attribute', 'route_id', 'origin_id', 'destination_id')},
            },
        ),
    ]
