# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-08-22 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0021_farerule'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='translation',
            name='uniq_translation_per_entity_and_lang',
        ),
    ]
