# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-08-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0019_scenario_edit_state_scenario_edited_data'),
        ('gtfs', '0022_remove_translation_uniq_translation_per_entity_and_lang'),
    ]

    operations = [
    ]
