# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-09-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0023_merge_20250828_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopidkeyword',
            name='stop_group_name_label',
            field=models.CharField(default='label', max_length=200),
        ),
        migrations.AddField(
            model_name='stopnamekeywords',
            name='stop_group_id_label',
            field=models.CharField(default='SG000000', max_length=200),
        ),
    ]
