# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-09-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0024_stopidkeyword_stop_group_name_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fareattribute',
            name='agency_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
