# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-10-07 06:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0025_alter_fareattribute_agency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='prefecture_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, help_text='Path to the prefecture GTFS data file.', size=None),
        ),
        migrations.AddField(
            model_name='scenario',
            name='region_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, help_text='Path to the region GTFS data file.', size=None),
        ),
    ]
