# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-10-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0026_scenario_prefecture_info_scenario_region_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='graph_status',
            new_name='drm_graph_status',
        ),
        migrations.AddField(
            model_name='scenario',
            name='osm_graph_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('built', 'Built'), ('failed', 'Failed'), ('rebuilding', 'Rebuilding'), ('rebuilt', 'Rebuilt'), ('rebuild_failed', 'Rebuild Failed')], default='pending', max_length=20),
        ),
    ]
