# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-11-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0027_rename_graph_status_scenario_drm_graph_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stops',
            name='platform_code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stoptimes',
            name='timepoint',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Approximate time'), (1, 'Exact time')], help_text='GTFS timepoint: 1=exact, 0=approximate, null=unspecified', null=True),
        ),
        migrations.AlterField(
            model_name='stoptimes',
            name='shape_dist_traveled',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
