# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-11-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0028_stops_platform_code_stoptimes_timepoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='platform_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
