# Generated by Django 5.2.1 on 2025-11-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0029_alter_stops_platform_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='error_response',
            field=models.TextField(blank=True, help_text='Optional error response details', null=True),
        ),
    ]
