# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-11-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0029_alter_stops_platform_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trips',
            constraint=models.UniqueConstraint(fields=('scenario', 'trip_id'), name='unique_scenario_trip_id'),
        ),
    ]
