# Generated by Django 5.2.1 on 2025-11-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0030_trips_unique_scenario_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='stop_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_lon',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
