# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-11-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0030_notification_error_response'),
        ('gtfs', '0030_trips_unique_scenario_trip_id'),
    ]

    operations = [
    ]
