# Generated by Django 5.2.1 on 2025-11-20 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0031_alter_stops_stop_lat_alter_stops_stop_lon'),
        ('gtfs', '0031_merge_20251120_1521'),
    ]

    operations = [
    ]
