# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-11-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0032_merge_20251120_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoptimes',
            name='is_arrival_time_next_day',
            field=models.BooleanField(default=False, help_text='Indicates if the arrival time is on the next day.'),
        ),
        migrations.AddField(
            model_name='stoptimes',
            name='is_departure_time_next_day',
            field=models.BooleanField(default=False, help_text='Indicates if the departure time is on the next day.'),
        ),
    ]
