# Generated by Django 5.2.1 on 2025-11-25 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0033_stoptimes_is_arrival_time_next_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='scenario_name',
            field=models.CharField(error_messages={'unique': 'このシナリオ名は既に存在します。他の名前を選択してください。'}, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.UniqueConstraint(fields=('user', 'scenario_name'), name='unique_scenario_name_per_user'),
        ),
    ]
