# Generated by Django 5.2.1 on 2025-12-02 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0034_alter_scenario_scenario_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='agency_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agency',
            name='cemv_support',
            field=models.BooleanField(blank=True, help_text='Indicates contactless EMV support if provided by the feed.', null=True),
        ),
        migrations.AddField(
            model_name='farerule',
            name='contains_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='default_lang',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='feed_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='feed_contact_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='routes',
            name='cemv_support',
            field=models.BooleanField(blank=True, help_text='Indicates contactless EMV support at route level.', null=True),
        ),
        migrations.AddField(
            model_name='routes',
            name='continuous_drop_off',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routes',
            name='continuous_pickup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routes',
            name='jp_parent_route_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='routes',
            name='network_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='routes',
            name='route_sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stops',
            name='level_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stops',
            name='stop_access',
            field=models.IntegerField(blank=True, help_text='GTFS stop_access field, if provided.', null=True),
        ),
        migrations.AddField(
            model_name='stops',
            name='stop_timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stops',
            name='tts_stop_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stoptimes',
            name='continuous_drop_off',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stoptimes',
            name='continuous_pickup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stoptimes',
            name='drop_off_booking_rule_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stoptimes',
            name='end_pickup_drop_off_window',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stoptimes',
            name='location_group_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stoptimes',
            name='location_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stoptimes',
            name='pickup_booking_rule_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stoptimes',
            name='start_pickup_drop_off_window',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='record_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='translation',
            name='record_sub_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trips',
            name='bikes_allowed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='cars_allowed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='jp_office_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trips',
            name='jp_pattern_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trips',
            name='jp_trip_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='jp_trip_desc_symbol',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trips',
            name='wheelchair_accessible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GtfsImportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Standardized GTFS filename, e.g. stops.txt', max_length=100)),
                ('original_name', models.CharField(blank=True, help_text='Actual name in ZIP, in case it differs.', max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_files', to='gtfs.scenario')),
            ],
            options={
                'db_table': 'gtfs_imported_files',
            },
        ),
        migrations.CreateModel(
            name='GtfsImportedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Column name, e.g. stop_id, route_short_name', max_length=100)),
                ('column_index', models.IntegerField(help_text='0-based index in the original file header.')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('gtfs_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='gtfs.gtfsimportedfile')),
            ],
            options={
                'db_table': 'gtfs_imported_fields',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.CharField(max_length=200)),
                ('level_index', models.FloatField(help_text='0=ground, positive=above, negative=below')),
                ('level_name', models.CharField(blank=True, help_text='Human-readable level name', max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'levels',
            },
        ),
        migrations.CreateModel(
            name='LocationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_group_id', models.CharField(max_length=200)),
                ('location_group_name', models.CharField(max_length=255)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'location_groups',
            },
        ),
        migrations.CreateModel(
            name='LocationGroupStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('location_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='gtfs.locationgroup')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'location_group_stops',
            },
        ),
        migrations.CreateModel(
            name='OfficeJP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_id', models.CharField(max_length=200)),
                ('office_name', models.CharField(max_length=200)),
                ('office_url', models.URLField(blank=True, max_length=500)),
                ('office_phone', models.CharField(blank=True, max_length=50)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'office_jp',
            },
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway_id', models.CharField(max_length=200)),
                ('from_stop_id', models.CharField(max_length=200)),
                ('to_stop_id', models.CharField(max_length=200)),
                ('pathway_mode', models.IntegerField(help_text='1=walkway,2=stairs,3=travelator,4=escalator,5=elevator,6=fare gate,7=exit gate')),
                ('is_bidirectional', models.IntegerField(help_text='0=unidirectional, 1=bidirectional')),
                ('length', models.FloatField(blank=True, help_text='Pathway length in meters', null=True)),
                ('traversal_time', models.IntegerField(blank=True, help_text='Estimated traversal time in seconds', null=True)),
                ('stair_count', models.IntegerField(blank=True, help_text='Number of stairs', null=True)),
                ('max_slope', models.FloatField(blank=True, help_text='Maximum slope (rise/run)', null=True)),
                ('min_width', models.FloatField(blank=True, help_text='Minimum width in meters', null=True)),
                ('signposted_as', models.CharField(blank=True, help_text='Signed direction towards this pathway', max_length=200)),
                ('reversed_signposted_as', models.CharField(blank=True, help_text='Signed direction when traversed in reverse', max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'pathways',
            },
        ),
        migrations.CreateModel(
            name='PatternJP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jp_pattern_id', models.CharField(max_length=200)),
                ('route_update_date', models.DateField(blank=True, null=True)),
                ('origin_stop', models.CharField(blank=True, max_length=200)),
                ('via_stop', models.CharField(blank=True, max_length=200)),
                ('destination_stop', models.CharField(blank=True, max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'pattern_jp',
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop_id', models.CharField(max_length=200)),
                ('to_stop_id', models.CharField(max_length=200)),
                ('transfer_type', models.IntegerField(help_text='0=Recommended, 1=Timed, 2=Minimum time, 3=Not possible')),
                ('min_transfer_time', models.IntegerField(blank=True, help_text='Minimum transfer time in seconds', null=True)),
                ('from_route_id', models.CharField(blank=True, help_text='Optional: route_id from routes.txt', max_length=200)),
                ('to_route_id', models.CharField(blank=True, help_text='Optional: route_id from routes.txt', max_length=200)),
                ('from_trip_id', models.CharField(blank=True, help_text='Optional: trip_id from trips.txt', max_length=200)),
                ('to_trip_id', models.CharField(blank=True, help_text='Optional: trip_id from trips.txt', max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'transfers',
            },
        ),
        migrations.CreateModel(
            name='AgencyJP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(max_length=200)),
                ('agency_official_name', models.CharField(blank=True, max_length=200)),
                ('agency_zip_number', models.CharField(blank=True, max_length=20)),
                ('agency_address', models.CharField(blank=True, max_length=255)),
                ('agency_president_pos', models.CharField(blank=True, max_length=200)),
                ('agency_president_name', models.CharField(blank=True, max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'agency_jp',
                'unique_together': {('scenario', 'agency_id')},
            },
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribution_id', models.CharField(max_length=200)),
                ('agency_id', models.CharField(blank=True, max_length=200)),
                ('route_id', models.CharField(blank=True, max_length=200)),
                ('trip_id', models.CharField(blank=True, max_length=200)),
                ('organization_name', models.CharField(max_length=255)),
                ('is_producer', models.IntegerField(blank=True, help_text='1 if organization is a producer, else 0/empty', null=True)),
                ('is_operator', models.IntegerField(blank=True, help_text='1 if organization is an operator, else 0/empty', null=True)),
                ('is_authority', models.IntegerField(blank=True, help_text='1 if organization is an authority, else 0/empty', null=True)),
                ('attribution_url', models.URLField(blank=True, max_length=500)),
                ('attribution_email', models.EmailField(blank=True, max_length=254)),
                ('attribution_phone', models.CharField(blank=True, max_length=50)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'attributions',
                'constraints': [models.UniqueConstraint(fields=('scenario', 'attribution_id'), name='unique_attribution_per_scenario')],
            },
        ),
        migrations.CreateModel(
            name='BookingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_rule_id', models.CharField(max_length=200)),
                ('booking_type', models.IntegerField(help_text='1/2/... as per GTFS-Flex booking_type')),
                ('prior_notice_duration_min', models.IntegerField(blank=True, help_text='Minimum prior notice, in minutes', null=True)),
                ('prior_notice_start_day', models.IntegerField(blank=True, help_text='How many days before service booking becomes possible', null=True)),
                ('prior_notice_start_time', models.TimeField(blank=True, help_text='Local time when booking window opens on start day', null=True)),
                ('prior_notice_last_day', models.IntegerField(blank=True, help_text='How many days before service booking closes', null=True)),
                ('prior_notice_last_time', models.TimeField(blank=True, help_text='Local time when booking window closes on last day', null=True)),
                ('message', models.TextField(blank=True, help_text='Free-text description of booking rules')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for booking', max_length=50)),
                ('info_url', models.URLField(blank=True, help_text='URL with info about the service', max_length=500)),
                ('booking_url', models.URLField(blank=True, help_text='Direct URL to booking interface', max_length=500)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'booking_rules',
                'constraints': [models.UniqueConstraint(fields=('scenario', 'booking_rule_id'), name='unique_booking_rule_per_scenario')],
            },
        ),
        migrations.CreateModel(
            name='Frequencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('headway_secs', models.IntegerField()),
                ('exact_times', models.IntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'frequencies',
                'indexes': [models.Index(fields=['scenario', 'trip_id'], name='frequencies_scenari_46bdc4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='gtfsimportedfile',
            constraint=models.UniqueConstraint(fields=('scenario', 'file_name'), name='unique_gtfs_file_per_scenario'),
        ),
        migrations.AddIndex(
            model_name='gtfsimportedfield',
            index=models.Index(fields=['gtfs_file', 'column_index'], name='gtfs_import_gtfs_fi_a5508f_idx'),
        ),
        migrations.AddConstraint(
            model_name='gtfsimportedfield',
            constraint=models.UniqueConstraint(fields=('gtfs_file', 'field_name'), name='unique_field_per_file'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('scenario', 'level_id'), name='unique_level_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='locationgroup',
            constraint=models.UniqueConstraint(fields=('scenario', 'location_group_id'), name='unique_location_group_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='locationgroupstop',
            constraint=models.UniqueConstraint(fields=('scenario', 'location_group', 'stop_id'), name='unique_location_group_stop_per_scenario'),
        ),
        migrations.AlterUniqueTogether(
            name='officejp',
            unique_together={('scenario', 'office_id')},
        ),
        migrations.AddConstraint(
            model_name='pathway',
            constraint=models.UniqueConstraint(fields=('scenario', 'pathway_id'), name='unique_pathway_per_scenario'),
        ),
        migrations.AlterUniqueTogether(
            name='patternjp',
            unique_together={('scenario', 'jp_pattern_id')},
        ),
        migrations.AddConstraint(
            model_name='transfers',
            constraint=models.UniqueConstraint(fields=('scenario', 'from_stop_id', 'to_stop_id', 'from_route_id', 'to_route_id', 'from_trip_id', 'to_trip_id'), name='unique_transfer_rule_per_scenario'),
        ),
    ]
