# Generated by Django 5.2.1 on 2025-12-01 08:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0034_alter_scenario_scenario_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GtfsValidationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notices', models.JSONField(default=list)),
                ('validated_at', models.DateTimeField(auto_now=True)),
                ('validator_version', models.CharField(blank=True, max_length=50)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_result', to='gtfs.scenario')),
            ],
            options={
                'db_table': 'gtfs_validation_results',
            },
        ),
    ]
