# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-12-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0035_agency_agency_email_agency_cemv_support_and_more'),
        ('gtfs', '0035_gtfsvalidationresult'),
    ]

    operations = [
    ]
