# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-12-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0036_merge_20251203_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='error_response',
            field=models.JSONField(blank=True, help_text='Optional error response details', null=True),
        ),
    ]
