# Generated by Django 5.2.1 on 2025-12-12 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0037_alter_notification_error_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedinfo',
            old_name='end_date',
            new_name='feed_end_date',
        ),
        migrations.RenameField(
            model_name='feedinfo',
            old_name='language',
            new_name='feed_lang',
        ),
        migrations.RenameField(
            model_name='feedinfo',
            old_name='publisher_name',
            new_name='feed_publisher_name',
        ),
        migrations.RenameField(
            model_name='feedinfo',
            old_name='publisher_url',
            new_name='feed_publisher_url',
        ),
        migrations.RenameField(
            model_name='feedinfo',
            old_name='start_date',
            new_name='feed_start_date',
        ),
        migrations.RenameField(
            model_name='feedinfo',
            old_name='version',
            new_name='feed_version',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    -- Drop any known/likely unique index names for fare_attributes(scenario_id, fare_id)
                    DROP INDEX IF EXISTS fare_attributes_scenario_id_fare_id_uniq;
                    DROP INDEX IF EXISTS fare_attributes_scenario_id_fare_id_key;
                    DROP INDEX IF EXISTS gtfs_fareattribute_scenario_id_fare_id_uniq;
                    """,
                    reverse_sql="""
                    -- Recreate a unique index if absent (best-effort)
                    CREATE UNIQUE INDEX IF NOT EXISTS fare_attributes_scenario_id_fare_id_uniq
                        ON fare_attributes (scenario_id, fare_id);
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='fareattribute',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    -- Drop any known/likely unique index names for fare_rules(scenario_id, fare_id, route_id, origin_id, destination_id)
                    DROP INDEX IF EXISTS fare_rules_scenario_id_fare_id_route_id_origin_id_destination_id_uniq;
                    DROP INDEX IF EXISTS fare_rules_scenario_id_fare_id_route_id_origin_id_destination_id_key;
                    DROP INDEX IF EXISTS gtfs_farerule_scenario_id_fare_id_route_id_origin_id_destination_id_uniq;
                    """,
                    reverse_sql="""
                    CREATE UNIQUE INDEX IF NOT EXISTS fare_rules_scenario_id_fare_id_route_id_origin_id_destination_id_uniq
                        ON fare_rules (scenario_id, fare_id, route_id, origin_id, destination_id);
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='farerule',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AddField(
            model_name='bookingrule',
            name='drop_off_message',
            field=models.TextField(blank=True, help_text='Message for drop-off-only scenarios.'),
        ),
        migrations.AddField(
            model_name='bookingrule',
            name='pickup_message',
            field=models.TextField(blank=True, help_text='Message for pickup-only scenarios.'),
        ),
        migrations.AddField(
            model_name='bookingrule',
            name='prior_notice_duration_max',
            field=models.IntegerField(blank=True, help_text='Maximum minutes before travel for booking (optional for booking_type=1 only).', null=True),
        ),
        migrations.AddField(
            model_name='bookingrule',
            name='prior_notice_service_id',
            field=models.CharField(blank=True, help_text='calendar.service_id used for counting days, optional for booking_type=2 only.', max_length=200),
        ),
        migrations.AddField(
            model_name='farerule',
            name='fare_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingrule',
            name='booking_type',
            field=models.IntegerField(help_text='0=real-time, 1=same-day with notice, 2=prior day(s)'),
        ),
        migrations.AlterField(
            model_name='bookingrule',
            name='booking_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='bookingrule',
            name='info_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='bookingrule',
            name='message',
            field=models.TextField(blank=True, help_text='General booking message for this rule.'),
        ),
        migrations.AlterField(
            model_name='bookingrule',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingrule',
            name='prior_notice_duration_min',
            field=models.IntegerField(blank=True, help_text='Minutes before travel to make request (required when booking_type=1).', null=True),
        ),
        migrations.AlterField(
            model_name='bookingrule',
            name='prior_notice_last_day',
            field=models.IntegerField(blank=True, help_text='Last day before travel for booking (required when booking_type=2).', null=True),
        ),
        migrations.AlterField(
            model_name='bookingrule',
            name='prior_notice_last_time',
            field=models.TimeField(blank=True, help_text='Last time on the last day to book (required if prior_notice_last_day is set).', null=True),
        ),
        migrations.AlterField(
            model_name='bookingrule',
            name='prior_notice_start_day',
            field=models.IntegerField(blank=True, help_text='Earliest day before travel to book (for some type 2 cases).', null=True),
        ),
        migrations.AlterField(
            model_name='bookingrule',
            name='prior_notice_start_time',
            field=models.TimeField(blank=True, help_text='Earliest time on earliest booking day (required if prior_notice_start_day is set).', null=True),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(max_length=200)),
                ('area_name', models.CharField(blank=True, max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'areas',
                'constraints': [models.UniqueConstraint(fields=('scenario', 'area_id'), name='unique_area_per_scenario')],
            },
        ),
        migrations.CreateModel(
            name='FareLegJoinRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_network_id', models.CharField(help_text='routes.network_id or networks.network_id', max_length=200)),
                ('to_network_id', models.CharField(help_text='routes.network_id or networks.network_id', max_length=200)),
                ('from_stop_id', models.CharField(blank=True, help_text='stops.stop_id', max_length=200)),
                ('to_stop_id', models.CharField(blank=True, help_text='stops.stop_id', max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'fare_leg_join_rules',
                'constraints': [models.UniqueConstraint(fields=('scenario', 'from_network_id', 'to_network_id', 'from_stop_id', 'to_stop_id'), name='unique_fare_leg_join_rule_per_scenario')],
            },
        ),
        migrations.CreateModel(
            name='FareLegRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_group_id', models.CharField(blank=True, help_text='Groups entries for transfer rules', max_length=200)),
                ('network_id', models.CharField(blank=True, help_text='routes.network_id or networks.network_id', max_length=200)),
                ('from_area_id', models.CharField(blank=True, help_text='areas.area_id', max_length=200)),
                ('to_area_id', models.CharField(blank=True, help_text='areas.area_id', max_length=200)),
                ('from_timeframe_group_id', models.CharField(blank=True, help_text='timeframes.timeframe_group_id', max_length=200)),
                ('to_timeframe_group_id', models.CharField(blank=True, help_text='timeframes.timeframe_group_id', max_length=200)),
                ('fare_product_id', models.CharField(help_text='fare_products.fare_product_id', max_length=200)),
                ('rule_priority', models.IntegerField(blank=True, help_text='Higher values = higher priority. Empty treated as 0.', null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'fare_leg_rules',
                'constraints': [models.UniqueConstraint(fields=('scenario', 'network_id', 'from_area_id', 'to_area_id', 'from_timeframe_group_id', 'to_timeframe_group_id', 'fare_product_id'), name='unique_fare_leg_rule_per_scenario')],
            },
        ),
        migrations.CreateModel(
            name='FareMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_media_id', models.CharField(max_length=200)),
                ('fare_media_name', models.CharField(blank=True, max_length=200)),
                ('fare_media_type', models.IntegerField(help_text='0=None, 1=Paper ticket, 2=Transit card, 3=cEMV, 4=Mobile app')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'fare_media',
                'constraints': [models.UniqueConstraint(fields=('scenario', 'fare_media_id'), name='unique_fare_media_per_scenario')],
            },
        ),
        migrations.CreateModel(
            name='FareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_product_id', models.CharField(max_length=200)),
                ('fare_product_name', models.CharField(blank=True, max_length=200)),
                ('rider_category_id', models.CharField(blank=True, help_text='rider_categories.rider_category_id', max_length=200)),
                ('fare_media_id', models.CharField(blank=True, help_text='fare_media.fare_media_id', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(help_text='ISO 4217 currency code (e.g. JPY, USD)', max_length=10)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'fare_products',
                'constraints': [models.UniqueConstraint(fields=('scenario', 'fare_product_id', 'rider_category_id', 'fare_media_id'), name='unique_fare_product_per_scenario')],
            },
        ),
        migrations.CreateModel(
            name='FareTransferRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_leg_group_id', models.CharField(blank=True, help_text='fare_leg_rules.leg_group_id (pre-transfer)', max_length=200)),
                ('to_leg_group_id', models.CharField(blank=True, help_text='fare_leg_rules.leg_group_id (post-transfer)', max_length=200)),
                ('transfer_count', models.IntegerField(blank=True, help_text='-1 = unlimited, >=1 = max consecutive transfers', null=True)),
                ('duration_limit', models.IntegerField(blank=True, help_text='Seconds; empty means no limit', null=True)),
                ('duration_limit_type', models.IntegerField(blank=True, help_text='0–3, defines how duration_limit is measured', null=True)),
                ('fare_transfer_type', models.IntegerField(help_text='0=A+AB, 1=A+AB+B, 2=AB')),
                ('fare_product_id', models.CharField(blank=True, help_text='fare_products.fare_product_id (transfer product)', max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'fare_transfer_rules',
                'constraints': [models.UniqueConstraint(fields=('scenario', 'from_leg_group_id', 'to_leg_group_id', 'fare_product_id', 'transfer_count', 'duration_limit'), name='unique_fare_transfer_rule_per_scenario')],
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_id', models.CharField(max_length=200)),
                ('network_name', models.CharField(blank=True, max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'networks',
                'constraints': [models.UniqueConstraint(fields=('scenario', 'network_id'), name='unique_network_per_scenario')],
            },
        ),
        migrations.CreateModel(
            name='RiderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_category_id', models.CharField(max_length=200)),
                ('rider_category_name', models.CharField(max_length=200)),
                ('is_default_fare_category', models.IntegerField(blank=True, choices=[(0, 'Not default'), (1, 'Default')], help_text='1 = default category, 0 or empty = not default', null=True)),
                ('eligibility_url', models.URLField(blank=True, max_length=500)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'rider_categories',
                'constraints': [models.UniqueConstraint(fields=('scenario', 'rider_category_id'), name='unique_rider_category_per_scenario')],
            },
        ),
        migrations.CreateModel(
            name='RouteNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_id', models.CharField(help_text='networks.network_id', max_length=200)),
                ('route_id', models.CharField(help_text='routes.route_id', max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'route_networks',
                'constraints': [models.UniqueConstraint(fields=('scenario', 'route_id'), name='unique_route_network_per_scenario')],
            },
        ),
        migrations.CreateModel(
            name='StopArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(help_text='areas.area_id', max_length=200)),
                ('stop_id', models.CharField(help_text='stops.stop_id', max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'stop_areas',
                'constraints': [models.UniqueConstraint(fields=('scenario', 'area_id', 'stop_id'), name='unique_stop_area_per_scenario')],
            },
        ),
        migrations.CreateModel(
            name='Timeframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe_group_id', models.CharField(max_length=200)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('service_id', models.CharField(max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'timeframes',
                'constraints': [models.UniqueConstraint(fields=('scenario', 'timeframe_group_id', 'service_id', 'start_time', 'end_time'), name='unique_timeframe_per_scenario')],
            },
        ),
    ]
