# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-12-15 01:55

import django.contrib.postgres.fields
from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField

def seed_safe_notice_rules(apps, schema_editor) -> None:
    Rule = apps.get_model("gtfs", "GtfsSafeNoticeRule")

    # Idempotent: do nothing if already seeded/managed by admin
    if Rule.objects.exists():
        return

    duplicate_key_allowed_files = [
        "translations.txt",
        "fare_attributes.txt",
        "fare_rules.txt",
    ]

    rules = [
        # === ERROR severity - safe only with specific conditions ===
        {
            "severity": "ERROR",
            "code": "missing_required_column",
            "sample_conditions": {"filename": "translations.txt"},
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "translations.txtのfield_name列が無いエラーは、旧形式のため問題ありません",
            "reason_en": "translations.txt missing field_name is old format, safe to ignore",
        },
        {
            "severity": "ERROR",
            "code": "duplicate_key",
            "sample_conditions": None,
            "allowed_filenames": duplicate_key_allowed_files,
            "skip": False,
            "reason_ja": "translations.txt、fare_attributes.txt、fare_rules.txtの重複行は、インポート時に処理されます",
            "reason_en": "Duplicate keys in translations/fare_attributes/fare_rules are handled during import",
        },

        # === LEGACY COMPATIBILITY - Shape/Geometry Issues ===
        {
            "severity": "ERROR",
            "code": "decreasing_shape_distance",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "shape_dist_traveledが単調増加していない。レガシーデータとの互換性のため許容します。",
            "reason_en": "Legacy compatibility: non-monotonic shape_dist_traveled accepted",
        },
        {
            "severity": "ERROR",
            "code": "equal_shape_distance_diff_coordinates",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "同じ距離で異なる座標がある。レガシーデータとの互換性のため許容します。",
            "reason_en": "Legacy compatibility: same distance with different coordinates accepted",
        },

        # === LEGACY COMPATIBILITY - Time/Scheduling Issues ===
        {
            "severity": "ERROR",
            "code": "block_trips_with_overlapping_stop_times",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "ブロック内のトリップの時刻が重複している。レガシーデータとの互換性のため許容します。",
            "reason_en": "Legacy compatibility: overlapping block trips accepted",
        },

        # === LEGACY COMPATIBILITY - Reference Issues ===
        {
            "severity": "ERROR",
            "code": "missing_trip_edge",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "トリップの開始または終了停留所が欠落している。レガシーデータとの互換性のため許容します。",
            "reason_en": "Legacy compatibility: missing trip edge accepted",
        },
        {
            "severity": "ERROR",
            "code": "translation_foreign_key_violation",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "翻訳が存在しないエンティティを参照している。レガシーデータとの互換性のため許容します。",
            "reason_en": "Legacy compatibility: translation FK violation accepted",
        },

        # === LEGACY COMPATIBILITY - Format/Syntax Issues ===
        {
            "severity": "ERROR",
            "code": "invalid_url",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "URLの形式が無効。レガシーデータとの互換性のため許容します。",
            "reason_en": "Legacy compatibility: invalid URL format accepted",
        },
        {
            "severity": "ERROR",
            "code": "u_r_i_syntax_error",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "URI構文エラー。レガシーデータとの互換性のため許容します。",
            "reason_en": "Legacy compatibility: URI syntax error accepted",
        },
        {
            "severity": "ERROR",
            "code": "translation_unexpected_value",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "翻訳に予期しない値がある。レガシーデータとの互換性のため許容します。",
            "reason_en": "Legacy compatibility: unexpected translation value accepted",
        },
        {
            "severity": "ERROR",
            "code": "invalid_character",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "無効な文字が含まれている。レガシーデータとの互換性のため許容します。",
            "reason_en": "Legacy compatibility: invalid character accepted",
        },

        # === LEGACY COMPATIBILITY - Range/Validation Issues ===
        {
            "severity": "ERROR",
            "code": "start_and_end_range_out_of_order",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "開始日と終了日の順序が逆。レガシーデータとの互換性のため許容します。",
            "reason_en": "Legacy compatibility: reversed date range accepted",
        },

        # === LEGACY COMPATIBILITY - Geographic Issues ===
        {
            "severity": "ERROR",
            "code": "point_near_origin",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "座標が原点(0,0)付近にある。レガシーデータとの互換性のため許容します。",
            "reason_en": "Legacy compatibility: coordinates near origin accepted",
        },
        {
            "severity": "ERROR",
            "code": "point_near_pole",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "座標が極付近にある。レガシーデータとの互換性のため許容します。",
            "reason_en": "Legacy compatibility: coordinates near pole accepted",
        },

        # === WARNING severity - generally safe for Japanese GTFS ===
        {
            "severity": "WARNING",
            "code": "missing_feed_contact_email_and_url",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "データ作成者の連絡先がないが、必須ではないので問題ありません。任意項目です。",
            "reason_en": "Feed contact info is optional",
        },
        {
            "severity": "WARNING",
            "code": "missing_recommended_field",
            "sample_conditions": {"filename": "fare_attributes.txt", "fieldName": "agency_id"},
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "agency_idが1つの場合は任意項目です",
            "reason_en": "agency_id in fare_attributes is optional when single agency",
        },
        {
            "severity": "WARNING",
            "code": "mixed_case_recommended_field",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "名称に大文字と小文字を含む必要がある。これは欧米語に対する警告ですので、日本語では無視してOKです。",
            "reason_en": "Mixed case warning is for Western languages, safe for Japanese",
        },
        {
            "severity": "WARNING",
            "code": "non_ascii_or_non_printable_char",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "idに非ASCII文字（全角文字）または印刷不能文字が使われている。日本語のIDを用いても実害は特にありません。",
            "reason_en": "Non-ASCII chars in Japanese IDs are acceptable",
        },
        {
            "severity": "WARNING",
            "code": "trip_coverage_not_active_for_next7_days",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "今後7日間有効なデータではない。データの開始日が将来のデータであれば問題ありません。",
            "reason_en": "Future start date is acceptable",
        },
        {
            "severity": "WARNING",
            "code": "missing_recommended_column",
            "sample_conditions": {"filename": "stop_times.txt", "fieldName": "timepoint"},
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "発着時刻精度timepointがないが、必須ではないので問題ありません。",
            "reason_en": "timepoint column in stop_times is optional",
        },

        # === INFO severity - always safe ===
        {
            "severity": "INFO",
            "code": "platform_without_parent_station",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "platform_codeが設定されているが親停留所が無い。現在のGTFSの仕様ではやむを得ない警告です。",
            "reason_en": "Platform without parent station is a known GTFS limitation",
        },
        {
            "severity": "INFO",
            "code": "unknown_file",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "GTFSの仕様で定義されていない名前のファイルがある。agency_jp.txtなど、jpがつくファイルは、GTFS-JPで拡張されたものなので、修正不要です。",
            "reason_en": "GTFS-JP extension files are acceptable",
        },
        {
            "severity": "INFO",
            "code": "unknown_column",
            "sample_conditions": None,
            "allowed_filenames": [],
            "skip": False,
            "reason_ja": "GTFSの仕様で定義されていない名前の列がある。jp_trip_descなど、jpで始まる名前の列は、GTFS-JPで拡張されたものなので、修正不要です。",
            "reason_en": "GTFS-JP extension columns are acceptable",
        },
    ]

    Rule.objects.bulk_create([Rule(**r) for r in rules], batch_size=200)

class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0038_rename_end_date_feedinfo_feed_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GtfsSafeNoticeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('ERROR', 'ERROR'), ('WARNING', 'WARNING'), ('INFO', 'INFO')], max_length=10)),
                ('code', models.CharField(max_length=200)),
                ('reason_ja', models.TextField()),
                ('reason_en', models.TextField()),
                ('sample_conditions', models.JSONField(blank=True, null=True)),
                ('allowed_filenames', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('skip', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gtfs_safe_notice_rules',
                'indexes': [models.Index(fields=['code', 'is_active'], name='gtfs_safe_n_code_0bf7a5_idx'), models.Index(fields=['severity', 'is_active'], name='gtfs_safe_n_severit_70890a_idx')],
            },
        ),
        migrations.RunPython(seed_safe_notice_rules, reverse_code=migrations.RunPython.noop),
    ]
