# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-12-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0039_gtfssafenoticerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtfssafenoticerule',
            name='is_fixable',
            field=models.BooleanField(default=False),
        ),
    ]
