# Generated by Django 5.2.1 on 2025-12-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0040_gtfssafenoticerule_is_fixable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptimes',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stoptimes',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
