# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2025-12-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0041_alter_stoptimes_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='stop_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
