# Generated by Django 5.2.1 on 2026-01-08 02:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0042_alter_stops_stop_lat_alter_stops_stop_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RidershipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic_card_agency_identification_code', models.CharField(help_text='事業会社が管理するICカードの識別番号IDiまたはカードの製造番号IDmを設定する', max_length=200)),
                ('ic_card_issuer_code', models.CharField(blank=True, help_text='ICカードの発行事業者を識別するコード', max_length=200)),
                ('ic_card_issuer_name', models.CharField(blank=True, help_text='ICカードの発行事業者名', max_length=200)),
                ('ic_card_feature_type', models.CharField(blank=True, choices=[('SF_CREDIT_AUTOCHARGE', 'SF_CREDIT_AUTOCHARGE'), ('SF_ONLY', 'SF_ONLY'), ('SF_NO_CREDIT', 'SF_NO_CREDIT')], help_text='ICカードに付帯されている機能を識別するコード', max_length=50)),
                ('ticket_type_area_code', models.CharField(blank=True, help_text='定期券などの対象となるエリアを識別するコード。ICカードに券種が存在する場合に設定', max_length=200)),
                ('ticket_type', models.CharField(blank=True, choices=[('SINGLE_TRIP_TICKET', 'SINGLE_TRIP_TICKET'), ('STUDENT_PASS', 'STUDENT_PASS'), ('COMMUTER_PASS', 'COMMUTER_PASS'), ('EXCURSION_TICKET', 'EXCURSION_TICKET'), ('ONE_DAY_PASS', 'ONE_DAY_PASS'), ('SHORT_TERM_PASS', 'SHORT_TERM_PASS')], help_text='チケットに付帯している券種を識別するコード', max_length=50)),
                ('ticket_type_name', models.CharField(blank=True, help_text='チケットに付帯している券種名', max_length=200)),
                ('ticket_valid_start_date', models.DateField(blank=True, help_text='定期券等ICカードを特有の券種として利用している場合の有効開始日', null=True)),
                ('ticket_valid_end_date', models.DateField(blank=True, help_text='定期券等ICカードを特有の券種として利用している場合の有効終了日', null=True)),
                ('ridership_record_id', models.IntegerField(help_text='システムが明細を管理するための一意のID')),
                ('transportation_mode_code', models.CharField(blank=True, help_text='利用した交通モードを識別するコード。GTFSを利用する場合、routes.txtの「route_type」を設定する', max_length=200)),
                ('ic_card_usage_detail_id', models.IntegerField(blank=True, help_text='ICカードが保持している一意のID。IDi、IDm単位の管理明細ID', null=True)),
                ('operating_agency_code', models.CharField(blank=True, help_text='運行事業者を識別するためのコード。GTFSを利用する場合、agency.txtの「agency_id」を設定', max_length=200)),
                ('operating_agency_name', models.CharField(blank=True, help_text='運行事業者名', max_length=200)),
                ('serviced_office_code', models.CharField(blank=True, help_text='営業所を識別するためのコード。GTFSを利用する場合、office_jp.txtの「office_id」を設定', max_length=200)),
                ('serviced_office_name', models.CharField(blank=True, help_text='営業所名。GTFSを利用する場合、office_jp.txtの「office_name」を設定', max_length=200)),
                ('route_pattern_id', models.CharField(blank=True, help_text='系統を識別するためのコード。GTFSを利用する場合、pattern_jp.txtの「jp_pattern_id」を設定する', max_length=200)),
                ('route_pattern_number', models.CharField(blank=True, help_text='バス事業者が系統の識別のために独自に定めている番号や記号。GTFSを利用する場合、routes.txtの「route_short_name」を設定', max_length=200)),
                ('service_line_name', models.CharField(blank=True, help_text='バス事業者が路線の識別のために独自に定めている番号や記号', max_length=200)),
                ('route_id', models.CharField(blank=True, help_text='経路を識別するためのコード。GTFSを利用する場合、routes.txtの「route_id」を設定する', max_length=200)),
                ('route_name', models.CharField(blank=True, help_text='経路名。GTFSを利用する場合、routes.txtの「route_long_name」を設定する', max_length=200)),
                ('trip_code', models.CharField(blank=True, help_text='路線・系統における便を識別するコード。GTFSを利用する場合、trips.txtの「trip_id」を設定する', max_length=200)),
                ('timetable_number', models.CharField(blank=True, help_text='バス事業者内部で使われる運行計画の識別番号', max_length=200)),
                ('vehicle_number', models.CharField(blank=True, help_text='それぞれのバス会社が独自に付与している識別番号', max_length=200)),
                ('operation_type', models.CharField(blank=True, choices=[('ENTRY', 'ENTRY'), ('EXIT', 'EXIT')], help_text='乗降実績に関連する処理を識別するコード', max_length=50)),
                ('operation_detail_type', models.CharField(blank=True, choices=[('DISCOUNT_TRANSFER', 'DISCOUNT_TRANSFER'), ('SPECIFIC_FARE', 'SPECIFIC_FARE'), ('ADDITIONAL_FARE', 'ADDITIONAL_FARE')], help_text='処理コードを参照しつつ、より細分化された情報を管理する', max_length=50)),
                ('boarding_area_code', models.CharField(blank=True, help_text='乗車駅(停留所)の地域を識別するためのコード', max_length=200)),
                ('boarding_station_sequence', models.IntegerField(blank=True, help_text='同一系統内で同じ停留所に複数回停車する場合、何回目の停車かを識別するための連番', null=True)),
                ('boarding_station_code', models.CharField(help_text='乗車した駅(停留所)を識別するコード。GTFSを利用する場合、stops.txtの「stop_id」を設定する', max_length=200)),
                ('boarding_station_name', models.CharField(blank=True, help_text='乗車した駅(停留所)名。GTFSを利用する場合、stops.txtの「stop_name」を設定する', max_length=200)),
                ('boarding_at', models.DateTimeField(blank=True, help_text='乗車した日時', null=True)),
                ('transfer_area_code_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='乗継駅(停留所)の地域を識別するためのコードのリスト', size=None)),
                ('transfer_station_code_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='乗継駅がある場合に、利用した駅(停留所)を識別するコードのリスト。GTFSを利用する場合、stops.txtの「stop_id」を設定する', size=None)),
                ('alighting_area_code', models.CharField(blank=True, help_text='降車駅(停留所)の地域を識別するためのコード', max_length=200)),
                ('alighting_station_sequence', models.IntegerField(blank=True, help_text='同一系統内で同じ停留所に複数回停車する場合、何回目の停車かを識別するための連番', null=True)),
                ('alighting_station_code', models.CharField(help_text='降車した駅(停留所)を識別するコード。GTFSを利用する場合、stops.txtの「stop_id」を設定する', max_length=200)),
                ('alighting_station_name', models.CharField(blank=True, help_text='降車した駅(停留所)名。GTFSを利用する場合、stops.txtの「stop_name」を設定する', max_length=200)),
                ('alighting_at', models.DateTimeField(blank=True, help_text='降車した日時', null=True)),
                ('payment_at', models.DateTimeField(help_text='精算日時。一件明細が作成された日時(鉄道であれば出場、バスであれば乗車もしくは降車の精算時)')),
                ('adult_challenged_passenger_count', models.IntegerField(blank=True, help_text='大人身障者利用人数', null=True)),
                ('adult_passenger_count', models.IntegerField(blank=True, help_text='大人利用人数', null=True)),
                ('child_challenged_passenger_count', models.IntegerField(blank=True, help_text='小児身障者利用人数', null=True)),
                ('child_passenger_count', models.IntegerField(blank=True, help_text='小児利用人数', null=True)),
                ('passenger_classification_type', models.CharField(blank=True, choices=[('ADULT', 'ADULT'), ('CHILD', 'CHILD'), ('INFANT', 'INFANT'), ('SENIOR', 'SENIOR'), ('DISABLED', 'DISABLED')], help_text='利用者の分類を識別するコード', max_length=50)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario')),
            ],
            options={
                'db_table': 'ridership_records',
                'indexes': [models.Index(fields=['scenario', 'payment_at'], name='ridership_r_scenari_f05a53_idx'), models.Index(fields=['scenario', 'boarding_station_code'], name='ridership_r_scenari_e5dd95_idx'), models.Index(fields=['scenario', 'alighting_station_code'], name='ridership_r_scenari_68ef28_idx'), models.Index(fields=['scenario', 'ic_card_agency_identification_code'], name='ridership_r_scenari_627d73_idx')],
                'constraints': [models.UniqueConstraint(fields=('scenario', 'ridership_record_id'), name='unique_ridership_record_per_scenario')],
            },
        ),
    ]
