# Generated by Django 5.2.1 on 2026-01-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0042_alter_stops_stop_lat_alter_stops_stop_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='drm_graph_build_fail_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='osm_graph_build_fail_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
