# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2026-01-08 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0043_ridershiprecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RidershipUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ridership_record_name', models.CharField(help_text='User-defined name/label to identify this ridership data upload', max_length=255)),
                ('file_name', models.CharField(help_text='Original filename of the uploaded Excel file', max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', help_text='Current status of the upload processing', max_length=20)),
                ('total_rows', models.IntegerField(default=0, help_text='Total number of rows in the uploaded file')),
                ('success_rows', models.IntegerField(default=0, help_text='Number of successfully imported rows')),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this upload')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the file was uploaded')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when processing was completed', null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ridership_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RidershipUploadError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_row_number', models.IntegerField(help_text='Row number in the original Excel file where the error occurred')),
                ('error_type', models.CharField(choices=[('validation', 'Validation Error'), ('parsing', 'Parsing Error'), ('duplicate', 'Duplicate Record'), ('missing_required', 'Missing Required Field'), ('invalid_format', 'Invalid Format'), ('invalid_value', 'Invalid Value'), ('reference', 'Reference Error'), ('unknown', 'Unknown Error')], default='unknown', help_text='Type/category of the error', max_length=50)),
                ('field_name', models.CharField(blank=True, help_text='Name of the field that caused the error (if applicable)', max_length=200)),
                ('error_message', models.TextField(help_text='Detailed error message')),
                ('raw_data', models.JSONField(blank=True, help_text='Original row data from the Excel file that failed to import', null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this error')),
            ],
            options={
                'db_table': 'ridership_upload_errors',
                'ordering': ['source_row_number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='ridershiprecord',
            name='unique_ridership_record_per_scenario',
        ),
        migrations.AddField(
            model_name='ridershiprecord',
            name='source_row_number',
            field=models.IntegerField(blank=True, help_text='Original row number in the uploaded Excel file', null=True),
        ),
        migrations.AddField(
            model_name='ridershipupload',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.scenario'),
        ),
        migrations.AddField(
            model_name='ridershipupload',
            name='user',
            field=models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ridershiprecord',
            name='ridership_upload',
            field=models.ForeignKey(default=None, help_text='Reference to the upload transaction this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='gtfs.ridershipupload'),
        ),
        migrations.AddIndex(
            model_name='ridershiprecord',
            index=models.Index(fields=['ridership_upload', 'source_row_number'], name='ridership_r_ridersh_e1d686_idx'),
        ),
        migrations.AddConstraint(
            model_name='ridershiprecord',
            constraint=models.UniqueConstraint(fields=('ridership_upload', 'ridership_record_id'), name='unique_ridership_record_per_upload'),
        ),
        migrations.AddField(
            model_name='ridershipuploaderror',
            name='ridership_upload',
            field=models.ForeignKey(help_text='Reference to the upload transaction this error belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='gtfs.ridershipupload'),
        ),
        migrations.AddIndex(
            model_name='ridershipupload',
            index=models.Index(fields=['scenario', 'uploaded_at'], name='ridership_u_scenari_88be4e_idx'),
        ),
        migrations.AddIndex(
            model_name='ridershipupload',
            index=models.Index(fields=['user', 'uploaded_at'], name='ridership_u_user_id_39fa50_idx'),
        ),
        migrations.AddIndex(
            model_name='ridershipupload',
            index=models.Index(fields=['upload_status'], name='ridership_u_upload__6f881f_idx'),
        ),
        migrations.AddIndex(
            model_name='ridershipuploaderror',
            index=models.Index(fields=['ridership_upload', 'source_row_number'], name='ridership_u_ridersh_39c7c7_idx'),
        ),
        migrations.AddIndex(
            model_name='ridershipuploaderror',
            index=models.Index(fields=['ridership_upload', 'error_type'], name='ridership_u_ridersh_255261_idx'),
        ),
    ]
