# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2026-01-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0043_scenario_drm_graph_build_fail_log_and_more'),
        ('gtfs', '0044_ridershipupload_ridershipuploaderror_and_more'),
    ]

    operations = [
    ]

