# Generated by Django 5.2.1 on 2026-01-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0045_merge_20260116_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridershipupload',
            name='max_tolerance_time',
            field=models.IntegerField(blank=True, help_text='Maximum tolerance time in minutes for ridership data processing', null=True),
        ),
    ]
