# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2026-01-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0046_ridershipupload_max_tolerance_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridershipuploaderror',
            name='error_type',
            field=models.CharField(choices=[('validation', 'Validation Error'), ('parsing', 'Parsing Error'), ('duplicate', 'Duplicate Record'), ('missing_required', 'Missing Required Field'), ('invalid_format', 'Invalid Format'), ('invalid_value', 'Invalid Value'), ('reference', 'Reference Error'), ('trip_not_found', 'Trip Not Found'), ('unknown', 'Unknown Error')], default='unknown', help_text='Type/category of the error', max_length=50),
        ),
    ]
