# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
# Generated by Django 5.2.1 on 2026-02-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0047_alter_ridershipuploaderror_error_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtfssafenoticerule',
            name='severity',
            field=models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], max_length=10),
        ),
        migrations.AlterField(
            model_name='routes',
            name='continuous_drop_off',
            field=models.IntegerField(blank=True, choices=[(0, 'Regular'), (1, 'Not Available'), (2, 'Phone Agency'), (3, 'Coordinate With Driver')], null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='continuous_pickup',
            field=models.IntegerField(blank=True, choices=[(0, 'Regular'), (1, 'Not Available'), (2, 'Phone Agency'), (3, 'Coordinate With Driver')], null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='route_type',
            field=models.IntegerField(choices=[(0, 'Tram, Streetcar, Light rail'), (1, 'Subway, Metro'), (2, 'Rail (e.g., commuter rail)'), (3, 'Bus'), (4, 'Ferry'), (5, 'Cable car'), (6, 'Gondola, Suspended cable car'), (7, 'Funicular'), (11, 'Trolleybus'), (12, 'Monorail')], default=3),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='deletion_state',
            field=models.CharField(choices=[('active', 'Active'), ('deletion_pending', 'Deletion Pending'), ('failed', 'Failed')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='edit_state',
            field=models.CharField(choices=[('original', 'Original'), ('edited', 'Edited')], default='original', max_length=100),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='stops_grouping_method',
            field=models.CharField(blank=True, choices=[('stop_name', 'Stop Name'), ('stop_id', 'Stop Id')], default='stop_name', help_text="Method to group stops. Default is 'stop_name'.", max_length=200),
        ),
        migrations.AlterField(
            model_name='stops',
            name='location_type',
            field=models.IntegerField(choices=[(0, 'Stop'), (1, 'Station'), (2, 'Entrance Exit'), (3, 'Generic Node'), (4, 'Boarding Area')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='wheelchair_boarding',
            field=models.IntegerField(blank=True, choices=[(0, 'No Info'), (1, 'Accessible'), (2, 'Not Accessible')], null=True),
        ),
        migrations.AlterField(
            model_name='stoptimes',
            name='continuous_drop_off',
            field=models.IntegerField(blank=True, choices=[(0, 'Regular'), (1, 'Not Available'), (2, 'Phone Agency'), (3, 'Coordinate With Driver')], null=True),
        ),
        migrations.AlterField(
            model_name='stoptimes',
            name='continuous_pickup',
            field=models.IntegerField(blank=True, choices=[(0, 'Regular'), (1, 'Not Available'), (2, 'Phone Agency'), (3, 'Coordinate With Driver')], null=True),
        ),
        migrations.AlterField(
            model_name='stoptimes',
            name='drop_off_type',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Not Available'), (2, 'Phone Agency'), (3, 'Coordinate With Driver')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stoptimes',
            name='pickup_type',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Not Available'), (2, 'Phone Agency'), (3, 'Coordinate With Driver')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='bikes_allowed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Info'), (1, 'Allowed'), (2, 'Not Allowed')], null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='cars_allowed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Info'), (1, 'Allowed'), (2, 'Not Allowed')], null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='direction_id',
            field=models.IntegerField(blank=True, choices=[(0, 'Outbound'), (1, 'Inbound')], null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='wheelchair_accessible',
            field=models.IntegerField(blank=True, choices=[(0, 'No Info'), (1, 'Accessible'), (2, 'Not Accessible')], null=True),
        ),
    ]
