# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
class ErrorMessages:
    """Centralized error codes for API responses."""
    
    # General errors
    VALIDATION_ERROR = 'VALIDATION_ERROR'
    NOT_FOUND = 'NOT_FOUND'
    PERMISSION_DENIED = 'PERMISSION_DENIED'
    
    # User errors
    USER_NOT_FOUND = 'USER_NOT_FOUND'
    USERNAME_EXISTS = 'USERNAME_EXISTS'
    INVALID_PASSWORD = 'INVALID_PASSWORD'
    
    # Project errors
    PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND'
    PROJECT_NAME_EXISTS = 'PROJECT_NAME_EXISTS'
    USER_NOT_ASSIGNED = 'USER_NOT_ASSIGNED'
    USER_ALREADY_ASSIGNED = 'USER_ALREADY_ASSIGNED'
    
    # Organization errors
    ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND'
    ORGANIZATION_NAME_EXISTS = 'ORGANIZATION_NAME_EXISTS'
    ORGANIZATION_INACTIVE = 'ORGANIZATION_INACTIVE'
    NO_USERS_IN_ORGANIZATION = 'NO_USERS_IN_ORGANIZATION'
    
    # Role errors
    ROLE_NOT_FOUND = 'ROLE_NOT_FOUND'
    ROLE_NAME_EXISTS = 'ROLE_NAME_EXISTS'
    ROLE_HAS_USERS = 'ROLE_HAS_USERS'
    
    # Access errors
    ACCESS_NOT_FOUND = 'ACCESS_NOT_FOUND'
    ACCESS_CODE_EXISTS = 'ACCESS_CODE_EXISTS'
