# Generated by Django 5.2.1 on 2025-07-30 07:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeshLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meshcode', models.CharField(max_length=12, unique=True)),
                ('mcode', models.CharField(max_length=5)),
                ('prefecture_name', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('city_code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mesh_location',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PopulationMesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meshcode', models.CharField(max_length=12, unique=True)),
                ('mcode', models.CharField(max_length=5)),
                ('age_0_14', models.IntegerField(blank=True, null=True)),
                ('age_15_64', models.IntegerField(blank=True, null=True)),
                ('age_65_up', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=6668)),
            ],
            options={
                'verbose_name': 'Population Mesh',
                'verbose_name_plural': 'Population Meshes',
                'db_table': 'population_mesh',
            },
        ),
    ]
