# Generated by Django 5.2.1 on 2025-09-02 01:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_meshlocation_populationmesh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterests',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PoiBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poi_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'poi_batches',
            },
        ),
        migrations.AddField(
            model_name='pointofinterests',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='visualization.poibatch'),
        ),
        migrations.AddIndex(
            model_name='pointofinterests',
            index=models.Index(fields=['user', 'type'], name='point_of_in_user_id_a42c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='pointofinterests',
            index=models.Index(fields=['user', 'batch'], name='point_of_in_user_id_a61afb_idx'),
        ),
        migrations.AddIndex(
            model_name='poibatch',
            index=models.Index(fields=['user', 'created_at'], name='poi_batches_user_id_fe36d7_idx'),
        ),
        migrations.AddIndex(
            model_name='poibatch',
            index=models.Index(fields=['user', 'file_name'], name='poi_batches_user_id_a74606_idx'),
        ),
        migrations.AddConstraint(
            model_name='poibatch',
            constraint=models.UniqueConstraint(fields=('user', 'file_name'), name='uniq_poi_batch_filename_per_user'),
        ),
    ]
