# Generated by Django 5.2.1 on 2025-12-05 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('visualization', '0003_pointofinterests_remark_poibatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='poibatch',
            name='uniq_poi_batch_filename_per_user',
        ),
        migrations.AddField(
            model_name='poibatch',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='poibatch',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poi_batches', to='user.project'),
        ),
        migrations.AddField(
            model_name='pointofinterests',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='user.project'),
        ),
        migrations.AddIndex(
            model_name='pointofinterests',
            index=models.Index(fields=['project', 'type'], name='point_of_in_project_31a96c_idx'),
        ),
        migrations.AddIndex(
            model_name='pointofinterests',
            index=models.Index(fields=['project', 'batch'], name='point_of_in_project_2d2462_idx'),
        ),
        migrations.AddConstraint(
            model_name='poibatch',
            constraint=models.UniqueConstraint(fields=('user', 'project', 'file_name'), name='uniq_poi_batch_filename_per_user_project'),
        ),
        migrations.AddConstraint(
            model_name='pointofinterests',
            constraint=models.UniqueConstraint(fields=('user', 'project', 'batch', 'type', 'name', 'lat', 'lng'), name='uniq_poi_user_project_batch_type_name_lat_lng'),
        ),
    ]
