# Generated by Django 5.2.1 on 2025-12-27 00:00

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('visualization', '0004_remove_poibatch_uniq_poi_batch_filename_per_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPrefectureSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefecture_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_selection', to='user.project')),
            ],
            options={
                'db_table': 'project_prefecture_selections',
            },
        ),
    ]
