# Generated by Django 5.2.1 on 2026-01-05 00:00

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('visualization', '0005_projectprefectureselection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrefectureSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefecture_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_prefecture_selection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_prefecture_selections',
                'constraints': [models.UniqueConstraint(fields=('user',), name='uniq_user_prefecture_selection')],
            },
        ),
    ]
