# Copyright (c) 2025-2026 MLIT Japan
# SPDX-License-Identifier: MIT
class ErrorMessages:
    VALIDATION_ERROR = "Validation error"
    QUERY_PARAM_SIMULATION_REQUIRED = "Query param 'simulation' is required."
    QUERY_PARAMETER_SIMULATION_REQUIRED = "Query parameter 'simulation' is required."
    SIMULATION_REQUIRED = "simulation is required"
    SIMULATION_ID_QUERY_REQUIRED = "simulation_id query parameter is required."
    INVALID_QUERY = "Invalid query"
    INVALID_BODY = "Invalid body"
    SIMULATION_NOT_FOUND = "Simulation not found"
    SCENARIOS_MISSING = "Scenarios missing"
    FAILED_CAR_VOLUME = "Failed to retrieve car volume data."
    FAILED_BENEFIT_CALCULATIONS = "Failed to retrieve benefit calculations data."
    FILE_IS_REQUIRED = "file is required"
    NOT_FOUND = "not found"

    MISSING_SIMULATION_ID_MESSAGE = "simulation_id が必要です"
    SIMULATION_NOT_FOUND_MESSAGE = "Simulation {sim_id} が見つかりません。"
    NO_DATA_MESSAGE = "データが見つかりません。"

    SIM_INIT_MISSING_SIMULATION_ID = "simulation_id が必要です"
    SIM_INIT_MISSING_SIMULATION_ID_PARAM = "simulation_id パラメータが必要です"
    SIM_INIT_INITIAL_DATA_NOT_FOUND = "初期データは未登録です"
    SIM_INIT_INVALID_SERVICE_DATE = "運行日（service_date）が不正です"
    SIM_INIT_MISSING_SERVICE_ID = "サービスID（service_ids/service_id）が必要です"
    SIM_INIT_MISSING_NUMERIC_FIELD = "{field_names} が必要です"
    SIM_INIT_INVALID_NUMERIC = "数値が不正です"
    SIM_INIT_CSV_PARSE_ERROR = "CSV の解析中にエラーが発生しました"
    SIM_INIT_SIMULATION_NOT_FOUND = "シミュレーションが見つかりません"
    SIM_INIT_ALREADY_EXISTS = "既に初期データが存在します（編集不可）"
    SIM_INIT_INVALID_SERVICE_ID_FOR_DATE = "この日付に有効でないサービスIDがあります: {invalid}"
    SIM_INIT_NO_DIFFERENT_DATA = "シナリオ間で異なる路線がありません。便の編集を行ってください。"
    SIM_INIT_INTERNAL_ERROR = "内部エラーが発生しました"
    SIM_INIT_MISSING_SCENARIOS = "シミュレーションに紐づくシナリオが不足しています"
    SIM_INIT_MISSING_FILE = "比較する CSV ファイルを添付してください"
    SIM_INIT_NO_SCENARIOS = "シミュレーションに紐づくシナリオがありません"
    SIM_INIT_SCENARIO_NOT_FOUND = "シナリオが見つかりません"
    SIM_INIT_INVALID_DATE = "日付が不正です（YYYYMMDD または YYYY-MM-DD）"
    SIM_INIT_INVALID_SIMULATION_INPUT_ID = "指定された simulation_input_id は存在しません"
    SIM_INIT_CSV_PROCESSING_ERROR = "CSV の解析中にエラーが発生しました: {err}"
    SIM_INIT_FETCH_PREVIOUS_ERROR = "以前の検証結果の取得中にエラーが発生しました: {err}"
    SIM_INIT_SAVE_ERROR = "CSV の保存中にエラーが発生しました: {err}"
