/**
 * Japanese labels (form labels, field names).
 *
 * Purpose: collect Japanese form/input labels to keep terminology consistent.
 */

export const LABELS = {
    common: {
        startDate: "開始日",
        endDate: "終了日",
        serviceId: "運行日ID",
        status: "状態",
        direction: "往復区分",
        section: "運行区間",
        routeId: "路線ID",
        patternId: "運行パターンID",
        placeholder: "例: ",
        stopId: "停留所ID",
        stopName: "停留所名称",
        routeInfo: "路線情報",
        agencyId: "事業者ID",
        routeLongName: "路線名",
        all: "すべて",
        day: "曜日",
        shapeId: "経路形状ID",
        newShapeId: "新しい経路形状ID",
        selectedCount: (count, total) => `選択中: ${count}/${total}`,
        beforeEdit: "編集前",
        afterEdit: "編集後",
        legend: "凡例",
        route: "路線",
        undoAllChanges: "すべての変更を元に戻す",
        filter: "フィルター",
        unknown: "不明",
        timeRange: "タイムレンジ",
        hourSuffix: "時",
    },
    uploader: {
        emptyText:
            "ファイルをここにドラッグ＆ドロップ、またはクリックして選択してください",
        selectFilePrompt: "ファイルを選択してください",
        acceptLabelPrefix: "対応形式：",
    },
    days: {
        monday: "月",
        tuesday: "火",
        wednesday: "水",
        thursday: "木",
        friday: "金",
        saturday: "土",
        sunday: "日",
        mondayLong: "月曜",
        tuesdayLong: "火曜",
        wednesdayLong: "水曜",
        thursdayLong: "木曜",
        fridayLong: "金曜",
        saturdayLong: "土曜",
        sundayLong: "日曜",
    },
    calendar: {
        tabCalendar: "運行カレンダー",
        tabException: "特例日",
        inputServiceId: "運行日ID選択",
        serviceIdSelect: "サービスIDを選択",
        exampleWeekday: "例: 平日",
    },
    feedInfo: {
        publisherName: "提供組織名",
        publisherUrl: "提供組織 URL",
        language: "提供言語",
        periodStart: "有効期間開始日",
        periodEnd: "有効期間終了日",
        version: "提供データバージョン",
        publisherNameShort: "発行者名",
        publisherUrlShort: "発行者URL",
        versionShort: "バージョン",
    },
    gtfs: {
        serviceId: "service_id",
        directionId: "direction_id",
        startDate: "start_date",
        endDate: "end_date",
        stopId: "stop_id",
        stopName: "stop_name",
        stopLat: "stop_lat",
        stopLon: "stop_lon",
        stopCode: "stop_code",
        tripId: "trip_id",
        tripHeadsign: "trip_headsign",
        stopSequence: "stop_sequence",
        arrivalTime: "arrival_time",
        departureTime: "departure_time",
        tripShortName: "trip_short_name",
        routeId: "route_id",
        routePatternId: "pattern_id",
        routeType: "route_type",
        agencyId: "agency_id",
        routeShortName: "route_short_name",
        routeLongName: "route_long_name",
        shapeId: "shape_id",
    },
    route: {
        routeShortName: "路線略称",
        routeType: "路線タイプ",
        internalPatternId: "路線内の運行パターンID",
        editShape: "経路形状を編集",
        applyToPattern: "適用する運行パターンを選択",
        applyToPatternHint:
            "同じ経路形状IDを使用している運行パターンのみ表示しています。",
        createRoute: "新規路線作成",
        patternInfo: "運行パターン情報",
        autoIdHint: "※ IDは新規データ作成後に自動で採番されます。",
        routeInfoBasic: "路線情報（基本）",
        createNewPatternTab: "路線内の運行パターン新設",
        deletePatternTab: "路線内の運行パターン廃止",
        shortenRouteTab: "路線区間の短縮",
        routeColor: "路線カラー",
        routeLabelField: "路線ラベル",
        routeMonochrome: "路線単色",
        shapePoint: "経路ポイント",
        modifiedPoint: "変更・追加ポイント",
        selectedPoint: "選択中ポイント",
        editShapeScreen: "経路形状の編集画面",
        modifiedCount: (count) => `(${count}件の変更あり)`,
        patternMapHint:
            "運行パターンの地図（ポイントをドラッグして移動できます）",
        shapePointList: "経路ポイント一覧（クリックで地図にズーム）",
        autoGenerateShapeTooltip: "経路形状を自動生成",
        addPointTooltip: "選択したポイントの後に新しいポイントを追加",
        deletePointTooltip: "選択したポイントを削除",
        totalDistanceM: "累計距離 (m)",
        totalPoints: (count) => `合計: ${count} ポイント`,
        selectedPointIndex: (index) => ` | 選択中: ポイント ${index}`,
        modifiedCountBrief: (count) => `| 変更: ${count}件`,
        totalDistanceKm: (km, m) => `総距離: ${km} km (${m} m)`,
        routeLabel: "ルート",
        patternLabel: "パターン",
        routeMap: "経路図",
    },
    trip: {
        tripId: "便ID",
        tripHeadsign: "行先表示",
        tripShortName: "便略称",
        tripName: "便名称",
        tripInfo: "便情報",
        tripDetail: "便詳細",
        stopSettings: "停車駅の設定",
        stopSequence: "通過順位",
        arrivalTime: "到着時刻",
        departureTime: "出発時刻",
        tabTripList: "便一覧",
        tabDeleteTrip: "便を削除",
        stopOrder: "停留所の並び順",
        stopInput: "標柱入力",
        autofillTimes: "時刻の自動入力",
        autofillHint:
            "出発駅の到着時刻を基準にして、すべての停車駅に自動で時刻を入力します",
        nextDay: "※翌日",
        nextNextDay: "※翌々日",
        daysAfter: (off) => `※${off}日後`,
        inbound: "復路",
        outbound: "往路",
        reverseSequence: "逆停止シーケンスを作成する",
        selectStop: "停留所を選択",
        saving: "保存中...",
        stopSelectLabel: "標柱選択",
        totalTrips: "総便数",
        routeGroup: "路線グループ",
        stops: "停車駅",
        startPoint: "開始ポイント",
        endPoint: "終点ポイント",
        routeNameTable: "ルートの名",
        editMode: "編集モード",
        freqAdjustment: "頻度を増やす/減らす",
        totalTripsAfter: "変更後の総便数",
        perRoute: "路線別",
        perTrip: "便別",
        perTripEditing: "便別編集",
        allSections: "すべて区間",
        allDirections: "すべて往復区分",
        allServices: "すべてサービス",
        routeGrouping: "路線のグルーピング / 路線名",
        multiplier: "倍数",
        delta: "増減数",
        routeIdAndName: "路線略称/路線名",
        directionLabel: (id, label) => `${id}：${label}`,
        directionLabelHalf: (id, label) => `${id}: ${label}`,
    },
    stop: {
        poleId: "標柱ID",
        poleName: "標柱名称",
        latitude: "緯度",
        longitude: "経度",
        stopCode: "標柱番号",
        clickMapHint: "※ 地図をクリックして位置を設定できます",
        uniqueIdHint:
            "※ 同じIDを登録することはできません。必ず変更してください。",
        parentStopAutoHint:
            "※ 停留所IDと名称は新規データ作成後に自動で設定されます。",
        stopLat: "停留所緯度",
        stopLon: "停留所経度",
        stopLabel: "停留所ラベル",
        poleAndStop: "標柱/停留所",
        pole: "標柱",
    },
    translation: {
        listTitle: (count) => `翻訳一覧（${count}件）`,
        fieldName: "項目名",
        originalValue: "元の値",
        language: "言語",
        translation: "翻訳",
        itemStop: "停留所",
        addTranslation: "翻訳を追加",
    },
    map: {
        paleMap: "淡色地図",
        stdMap: "標準地図",
        blankMap: "白地図",
        photoMap: "写真",
    },
    file: {
        fileList: "ファイル一覧",
        noFiles: "ファイルがありません。",
        fileImport: "ファイルのインポート",
        addAnotherFile: "別のファイルを追加",
        selectCsvHint: "CSVファイルを選択してください。対応形式：",
    },
    poi: {
        checkResult: "チェック結果",
        totalFiles: "合計ファイル",
        totalValidRows: "有効行合計",
        checkDateTime: "チェック日時",
        valid: "有効",
        invalid: "無効",
        duplicateFileName: "ファイル名重複",
        duplicateFileHint:
            "同名ファイルが既に存在します。ファイル名を変更してください。",
        fileRemarks: "備考（ファイルレベル）",
        remarkExample: "例：チェック済み（2025-09-02）・ソース確認済み 等",
        invalidRows: (count) => `無効行（${count} 件）`,
        validRows: (count) => `有効行（${count} 件）`,
        none: "なし",
        rowNumber: "行",
        type: "タイプ",
        name: "名前",
        latitude: "緯度",
        longitude: "経度",
        reason: "理由",
        remarks: "備考",
        importTitle: "施設データ インポート",
        map: "地図",
        list: "一覧",
        dropHint:
            "ファイルをここにドラッグ＆ドロップ、またはクリックして選択してください",
        formatCsv: "対応形式：CSV",
        cannotOperate: "現在は操作できません",
        csvFormatGuide: (type, name, lat, lng, remark) =>
            `CSVファイルのフォーマットは、以下の通りです：「${type}」, 「${name}」, 「${lat}」, 「${lng}」, 「${remark}」`,
        csvExample: (type, name, lat, lng, remark) =>
            `例： 「${type}」, 「${name}」, ${lat}, ${lng}, 「${remark}」`,
        otherTypeNote:
            "上記以外のタイプを入力した場合はデフォルトのアイコンになります",
        downloadTemplate: "テンプレートをダウンロード",
        dataList: "インポートした施設データ一覧",
        csvFile: "CSVファイル",
        facilityType: "施設データタイプ",
        facilityName: "施設データ名称",
        defaultData: "デフォルト（国土数値情報の施設データ）",
        targetPrefecture: "対象都道府県",
        scenarioStandard: "シナリオ標準（全域）",
        prefectureHint: "POIの表示範囲となる都道府県を指定できます",
        prefectureInactiveHint: "デフォルトデータを選択すると設定できます",
        createdAt: "追加日時",
        totalCount: (count) => `合計 ${count} 件`,
        deleteConfirmTitle: "CSVファイル削除の確認",
        deleteConfirmMsg: (label) =>
            `「${label}」に含まれるすべての施設データを削除します。よろしいですか？`,
        expand: "展開する",
        collapse: "折り畳む",
    },
};
